/**
 * Configuration Type Definitions
 *
 * Defines the TypeScript interfaces for the Blend65 project configuration
 * system. These types support the `blend65.json` project configuration file,
 * similar to TypeScript's `tsconfig.json`.
 *
 * **Key Interfaces:**
 * - {@link Blend65Config} - Main project configuration
 * - {@link CompilerOptions} - Compiler-specific options
 * - {@link EmulatorConfig} - Emulator configuration for `blend65 run`
 * - {@link ResourceConfig} - Asset pipeline configuration (future)
 *
 * **Integration with Existing Types:**
 * - `CompilerOptions.target` → maps to `TargetArchitecture` enum
 * - `CompilerOptions.optimization` → maps to `OptimizationLevel` enum
 *
 * @module config/types
 * @see {@link ../target/architecture.js!TargetArchitecture}
 * @see {@link ../optimizer/options.js!OptimizationLevel}
 */

/**
 * Target platform identifiers
 *
 * String literals that map to `TargetArchitecture` enum values.
 * Used in JSON configuration files for human-readable target selection.
 *
 * **Note**: Currently only 'c64' is implemented. Other targets
 * ('c128', 'x16') will generate a "not implemented yet" error.
 */
export type TargetPlatform = 'c64' | 'c128' | 'x16';

/**
 * Optimization level identifiers
 *
 * String literals that map to `OptimizationLevel` enum values.
 * Used in JSON configuration files for human-readable level selection.
 *
 * **Levels:**
 * - 'O0': No optimization (default)
 * - 'O1': Basic optimizations
 * - 'O2': Standard optimizations
 * - 'O3': Aggressive optimizations
 * - 'Os': Size optimization
 * - 'Oz': Minimum size optimization
 */
export type OptimizationLevelId = 'O0' | 'O1' | 'O2' | 'O3' | 'Os' | 'Oz';

/**
 * Debug information generation mode
 *
 * Controls what debug information is generated during compilation.
 *
 * - 'none': No debug info (smallest output)
 * - 'inline': Comments in generated assembly
 * - 'vice': VICE label file (.lbl) for debugging
 * - 'both': Inline comments + VICE labels
 */
export type DebugMode = 'none' | 'inline' | 'vice' | 'both';

/**
 * Output format for compiled programs
 *
 * Determines what files are generated by the compiler.
 *
 * - 'asm': Assembly source only (.asm)
 * - 'prg': C64 executable (.prg) - requires ACME assembler
 * - 'crt': Cartridge image (.crt) - not yet implemented
 * - 'both': Assembly + PRG files
 */
export type OutputFormat = 'asm' | 'prg' | 'crt' | 'both';

/**
 * Emulator type for argument formatting
 *
 * Identifies the emulator type for correct command-line argument formatting.
 *
 * - 'vice': VICE emulator (x64sc, x64, x128)
 * - 'x16emu': Commander X16 emulator
 */
export type EmulatorType = 'vice' | 'x16emu';

/**
 * Compiler-specific options
 *
 * Configures how the Blend65 compiler processes and generates code.
 * These options can be set in `blend65.json` and overridden via CLI flags.
 *
 * @example
 * ```typescript
 * const options: CompilerOptions = {
 *   target: 'c64',
 *   optimization: 'O0',
 *   debug: 'both',
 *   outDir: './build',
 *   outFile: 'game.prg',
 *   verbose: true,
 * };
 * ```
 */
export interface CompilerOptions {
  /**
   * Target platform
   * @default "c64"
   */
  target?: TargetPlatform;

  /**
   * Optimization level
   * @default "O0"
   */
  optimization?: OptimizationLevelId;

  /**
   * Debug information generation
   * @default "none"
   */
  debug?: DebugMode;

  /**
   * Output directory for compiled files
   * @default "./build"
   */
  outDir?: string;

  /**
   * Output filename (without path)
   * @example "game.prg"
   */
  outFile?: string;

  /**
   * Output format
   * @default "prg"
   */
  outputFormat?: OutputFormat;

  /**
   * Enable verbose compiler output
   * @default false
   */
  verbose?: boolean;

  /**
   * Enable strict mode (warnings as errors)
   * @default false
   */
  strict?: boolean;

  /**
   * Program load address
   * @default 2049 (0x0801)
   */
  loadAddress?: number;

  /**
   * Optional libraries to load
   * @example ["sid", "sprites"]
   */
  libraries?: string[];
}

/**
 * Emulator configuration
 *
 * Configures how `blend65 run` launches the emulator.
 * Supports VICE and Commander X16 emulators.
 */
export interface EmulatorConfig {
  /** Path to emulator executable */
  path?: string;

  /** Emulator type */
  type?: EmulatorType;

  /** Additional command-line arguments */
  args?: string[];

  /** Automatically run program after loading */
  autoRun?: boolean;

  /** Wait for emulator to exit */
  waitForExit?: boolean;
}

/**
 * Resource configuration (future)
 *
 * Configuration for the asset pipeline.
 * Specifies patterns for resource files that should be
 * processed and included in the build.
 */
export interface ResourceConfig {
  /** Sprite file patterns */
  sprites?: string[];

  /** Music file patterns */
  music?: string[];

  /** Character set patterns */
  charsets?: string[];
}

/**
 * Blend65 project configuration
 *
 * Main configuration interface for `blend65.json` project files.
 * Similar to TypeScript's `tsconfig.json`.
 */
export interface Blend65Config {
  /** JSON Schema reference for IDE support */
  $schema?: string;

  /** Compiler options */
  compilerOptions: CompilerOptions;

  /** Glob patterns for source files to include */
  include?: string[];

  /** Glob patterns for files to exclude */
  exclude?: string[];

  /** Explicit list of files to compile */
  files?: string[];

  /** Root directory for source files */
  rootDir?: string;

  /** Emulator configuration */
  emulator?: EmulatorConfig;

  /** Resource file mappings (future) */
  resources?: ResourceConfig;
}

/**
 * Configuration validation error
 */
export interface ConfigValidationError {
  /** JSON path to the invalid property */
  path: string;

  /** Human-readable error message */
  message: string;

  /** The invalid value that caused the error */
  value: unknown;
}

/**
 * Options for loading configuration
 */
export interface ConfigLoadOptions {
  /** Explicit path to configuration file */
  configPath?: string;

  /** Working directory for file resolution */
  cwd?: string;

  /** CLI overrides for compiler options */
  cliOverrides?: Partial<CompilerOptions>;

  /** Files specified on command line */
  cliFiles?: string[];

  /** Libraries specified on command line */
  cliLibraries?: string[];
}
