#!/usr/bin/env bash
# =============================================================================
# batch/runner.sh — Per-test execution for batch diagnostics
# =============================================================================
#
# Runs diag_app.sh (and optionally diag_vice.sh) for a single test program,
# collects results, and stores them in global arrays for report generation.
#
# Each test produces:
#   - Compilation results at all optimization levels (via diag_app.sh)
#   - VICE runtime verification results (if expected.json exists)
#   - Summary data extracted from diag_app.sh's summary.txt
#
# Requires: batch/env.sh to be sourced first
#
# =============================================================================

# ---------------------------------------------------------------------------
# Global result arrays (populated by run_all_tests)
# ---------------------------------------------------------------------------

# Per-test results — indexed same as BATCH_TESTS
declare -a BATCH_DIAG_EXIT=()       # diag_app.sh exit code per test
declare -a BATCH_BLEND_PASS=()      # Count of levels that compiled OK
declare -a BATCH_BLEND_TOTAL=()     # Total levels attempted
declare -a BATCH_ACME_PASS=()       # Count of levels assembled OK
declare -a BATCH_ACME_TOTAL=()      # Total levels with compilation output
declare -a BATCH_VICE_STATUS=()     # "pass"/"fail"/"skip"
declare -a BATCH_VICE_DETAIL=()     # e.g., "4/4 checks" or "skip"
declare -a BATCH_O0_PRG_SIZE=()     # O0 PRG size in bytes (baseline)
declare -a BATCH_O3_PRG_SIZE=()     # O3 PRG size in bytes (most optimized)
declare -a BATCH_SIZE_REGRESSIONS=() # Count of size regressions per test
declare -a BATCH_WARNINGS=()        # Warning count per test

# Counters
BATCH_TOTAL_PASS=0
BATCH_TOTAL_FAIL=0
BATCH_TOTAL_SKIP=0

# ---------------------------------------------------------------------------
# run_single_test() — Execute diagnostics for one test program
#
# Runs diag_app.sh on the blend file, then optionally runs diag_vice.sh
# if an expected.json exists. Extracts summary data from the output.
#
# Arguments:
#   $1 — Index into BATCH_TESTS array
#   $2 — Batch output directory (test output goes into a subfolder)
#
# Populates the global result arrays at position $1.
#
# Returns:
#   0 if test passed (all compilations + assembly + VICE OK)
#   1 if test had any failures
# ---------------------------------------------------------------------------
run_single_test() {
  local idx="$1"
  local batch_output="$2"

  local blend_file="${BATCH_TESTS[$idx]}"
  local test_name="${BATCH_TEST_NAMES[$idx]}"
  local test_dir="${BATCH_TEST_DIRS[$idx]}"
  local has_expected="${BATCH_HAS_EXPECTED[$idx]}"
  local test_output="$batch_output/$test_name"

  batch_subheader "[$((idx + 1))/$BATCH_TEST_COUNT] $test_name"

  # --- Run diag_app.sh ---
  local diag_exit=0
  local diag_log="$test_output/diag_app.log"
  mkdir -p "$test_output"

  bash "$DIAG_APP_SCRIPT" "$blend_file" "$test_output" > "$diag_log" 2>&1 || diag_exit=$?
  BATCH_DIAG_EXIT[$idx]=$diag_exit

  if [[ "$diag_exit" -eq 0 ]]; then
    batch_ok "diag_app: All compilations and assemblies passed"
  elif [[ "$diag_exit" -eq 1 ]]; then
    batch_fail "diag_app: One or more steps failed"
  else
    batch_fail "diag_app: Error (exit code $diag_exit)"
  fi

  # --- Extract summary data from diag_app.sh output ---
  _extract_summary_data "$idx" "$test_output"

  # --- Run VICE verification (if expected.json exists) ---
  if [[ "$has_expected" == "yes" ]]; then
    _run_vice_for_test "$idx" "$test_output" "$test_dir"
  else
    BATCH_VICE_STATUS[$idx]="skip"
    BATCH_VICE_DETAIL[$idx]="no expected.json"
    batch_info "VICE: skipped (no expected.json)"
  fi

  echo ""

  # Determine overall pass/fail
  if [[ "$diag_exit" -eq 0 && "${BATCH_VICE_STATUS[$idx]}" != "fail" ]]; then
    return 0
  else
    return 1
  fi
}

# ---------------------------------------------------------------------------
# _extract_summary_data() — Parse diag_app.sh summary.txt for metrics
#
# Extracts compilation/assembly pass counts, PRG sizes, and warning counts
# from the summary.txt generated by diag_app.sh.
#
# Arguments:
#   $1 — Index into result arrays
#   $2 — Test output directory (contains summary.txt)
# ---------------------------------------------------------------------------
_extract_summary_data() {
  local idx="$1"
  local test_output="$2"
  local summary="$test_output/summary.txt"

  # Defaults
  BATCH_BLEND_PASS[$idx]=0
  BATCH_BLEND_TOTAL[$idx]=0
  BATCH_ACME_PASS[$idx]=0
  BATCH_ACME_TOTAL[$idx]=0
  BATCH_O0_PRG_SIZE[$idx]=0
  BATCH_O3_PRG_SIZE[$idx]=0
  BATCH_SIZE_REGRESSIONS[$idx]=0
  BATCH_WARNINGS[$idx]=0

  if [[ ! -f "$summary" ]]; then
    batch_warn "No summary.txt found — cannot extract metrics"
    return
  fi

  # Count PASS/FAIL lines from the results table
  # Format: "  O0     | ✅ PASS   | ✅ PASS   | 116        | 1884 B     | 94 B"
  # Note: We grep for optimization level lines directly rather than using sed
  # range extraction, because the blank line after the "====" header would
  # prematurely terminate a sed range before reaching the actual data rows.
  local blend_pass=0
  local blend_total=0
  local acme_pass=0
  local acme_total=0

  while IFS= read -r line; do
    # Extract Blend65 column (2nd pipe-delimited field) and ACME column (3rd)
    local blend_col acme_col
    blend_col=$(echo "$line" | awk -F'|' '{print $2}')
    acme_col=$(echo "$line" | awk -F'|' '{print $3}')

    blend_total=$((blend_total + 1))

    # Check Blend65 result
    if echo "$blend_col" | grep -q "PASS"; then
      blend_pass=$((blend_pass + 1))
    fi

    # Check ACME result (only count if column has PASS or FAIL)
    if echo "$acme_col" | grep -q "PASS"; then
      acme_pass=$((acme_pass + 1))
      acme_total=$((acme_total + 1))
    elif echo "$acme_col" | grep -q "FAIL"; then
      acme_total=$((acme_total + 1))
    fi
  done < <(grep -E '^\s+O[0-3sz][sz]?\s+\|.*(PASS|FAIL)' "$summary")

  BATCH_BLEND_PASS[$idx]=$blend_pass
  BATCH_BLEND_TOTAL[$idx]=$blend_total
  BATCH_ACME_PASS[$idx]=$acme_pass
  BATCH_ACME_TOTAL[$idx]=$acme_total

  # Extract O0 PRG size from the results table (filter with PASS/FAIL to avoid
  # matching the PRG Binary Validation table which has the same O-level prefix)
  local o0_prg
  o0_prg=$(grep -E '^\s+O0\s+\|.*(PASS|FAIL)' "$summary" | awk -F'|' '{print $NF}' | tr -d ' B' | head -1)
  if [[ -n "$o0_prg" && "$o0_prg" =~ ^[0-9]+$ ]]; then
    BATCH_O0_PRG_SIZE[$idx]=$o0_prg
  fi

  # Extract O3 PRG size
  local o3_prg
  o3_prg=$(grep -E '^\s+O3\s+\|.*(PASS|FAIL)' "$summary" | awk -F'|' '{print $NF}' | tr -d ' B' | head -1)
  if [[ -n "$o3_prg" && "$o3_prg" =~ ^[0-9]+$ ]]; then
    BATCH_O3_PRG_SIZE[$idx]=$o3_prg
  fi

  # Count size regressions
  # Note: grep -c returns exit code 1 when count=0; use subshell to avoid pipefail issues
  local reg_count
  reg_count=$(grep -c "SIZE REGRESSION" "$summary" 2>/dev/null) || reg_count=0
  BATCH_SIZE_REGRESSIONS[$idx]=$reg_count

  # Count warnings (⚠️ occurrences in summary)
  local warn_count
  warn_count=$(grep -c "⚠" "$summary" 2>/dev/null) || warn_count=0
  BATCH_WARNINGS[$idx]=$warn_count
}

# ---------------------------------------------------------------------------
# _run_vice_for_test() — Run VICE verification on O0 build of a test
#
# Runs diag_vice.sh on the O0 PRG (unoptimized baseline) to verify
# runtime correctness. Only called when expected.json exists.
#
# Arguments:
#   $1 — Index into result arrays
#   $2 — Test output directory
#   $3 — Test source directory (contains expected.json)
# ---------------------------------------------------------------------------
_run_vice_for_test() {
  local idx="$1"
  local test_output="$2"
  local test_dir="$3"

  local expected="$test_dir/expected.json"
  local prg="$test_output/O0/output.prg"
  local labels="$test_output/O0/output.labels"
  local vice_output="$test_output/O0/vice"

  # Check if O0 PRG was produced
  if [[ ! -f "$prg" ]]; then
    BATCH_VICE_STATUS[$idx]="skip"
    BATCH_VICE_DETAIL[$idx]="no O0 PRG"
    batch_warn "VICE: skipped (O0 PRG not available)"
    return
  fi

  # Build VICE arguments
  local vice_args=("$prg" "$expected" "$vice_output")
  if [[ -f "$labels" ]]; then
    vice_args+=("--labels" "$labels")
  fi

  # Run VICE verification
  local vice_exit=0
  local vice_log="$test_output/vice-run.log"
  bash "$DIAG_VICE_SCRIPT" "${vice_args[@]}" > "$vice_log" 2>&1 || vice_exit=$?

  # Check VICE results
  local vice_summary="$vice_output/vice-summary.txt"
  if [[ -f "$vice_summary" ]]; then
    if grep -q "ALL CHECKS PASSED" "$vice_summary" 2>/dev/null; then
      BATCH_VICE_STATUS[$idx]="pass"
      # Extract check count from summary (e.g., "4/4 checks passed")
      local check_detail
      check_detail=$(grep -o '[0-9]*/[0-9]* checks' "$vice_summary" | head -1)
      BATCH_VICE_DETAIL[$idx]="${check_detail:-all passed}"
      batch_ok "VICE: ${BATCH_VICE_DETAIL[$idx]} passed"
    else
      BATCH_VICE_STATUS[$idx]="fail"
      local check_detail
      check_detail=$(grep -o '[0-9]*/[0-9]* checks' "$vice_summary" | head -1)
      BATCH_VICE_DETAIL[$idx]="${check_detail:-failed}"
      batch_fail "VICE: ${BATCH_VICE_DETAIL[$idx]}"
    fi
  else
    # VICE ran but no summary — likely VICE not available or crashed
    if [[ "$vice_exit" -eq 3 ]]; then
      BATCH_VICE_STATUS[$idx]="skip"
      BATCH_VICE_DETAIL[$idx]="VICE not available"
      batch_warn "VICE: not available — skipped"
    else
      BATCH_VICE_STATUS[$idx]="fail"
      BATCH_VICE_DETAIL[$idx]="no summary (exit $vice_exit)"
      batch_fail "VICE: no summary produced (exit code $vice_exit)"
    fi
  fi
}

# ---------------------------------------------------------------------------
# run_all_tests() — Execute diagnostics for all discovered tests
#
# Iterates through all tests in BATCH_TESTS, running each one and
# collecting results. Continues after individual test failures.
#
# Arguments:
#   $1 — Batch output directory
#
# Returns:
#   0 if all tests passed, 1 if any test failed
# ---------------------------------------------------------------------------
run_all_tests() {
  local batch_output="$1"

  BATCH_TOTAL_PASS=0
  BATCH_TOTAL_FAIL=0
  BATCH_TOTAL_SKIP=0

  for i in "${!BATCH_TESTS[@]}"; do
    local test_result=0
    run_single_test "$i" "$batch_output" || test_result=$?

    if [[ "$test_result" -eq 0 ]]; then
      BATCH_TOTAL_PASS=$((BATCH_TOTAL_PASS + 1))
    else
      BATCH_TOTAL_FAIL=$((BATCH_TOTAL_FAIL + 1))
    fi
  done

  if [[ "$BATCH_TOTAL_FAIL" -eq 0 ]]; then
    return 0
  else
    return 1
  fi
}
