// Discriminator: is VICE+autostart deterministic across processes when the monitor
// is NOT touched until well after RUN?  PRG: long phase-1 (~168M cycles) so we can
// attach mid-phase-1 with zero pre-RUN monitor interference; then measure
// from=$082A → to=$0837 (a ~327k-cycle busy loop spanning ~20 IRQs).
// If W is EQUAL across processes → divergence in probe-determinism.mjs came from
// pre-RUN monitor stops. If DIFFER → inherent cross-process nondeterminism.
import { spawn } from "node:child_process";
import net from "node:net";
import fs from "node:fs";

const EXE = process.env.HOME + "/.local/bin/x64sc";
const SCRATCH = "/tmp/claude-1000/-home-gevik-workdir-github-blend65-ri-blend65-asm-parity/825bf4bb-a76e-4377-973b-ab5d10f602b5/scratchpad";
const PRG = `${SCRATCH}/det3.prg`;

// det3.prg is generated by the python one-liner (correct 15-byte stub → code at $0810).
// from-label = $082A (INC $D020, executed once), to-label = $0839 (INC $D021).
if (!fs.existsSync(PRG)) throw new Error("det3.prg missing — regenerate it first");
const FROM = 0x083a, TO = 0x0847; // INC $D020 / INC $D021 instruction starts (verified offsets)

const CMD_HEADER = 11, RESP_HEADER = 12;

async function runOnce(bport, attachDelayMs) {
  const tport = bport + 1;
  let nextId = 1, acc = new Uint8Array(0), stopWaiter = null;
  const pending = new Map();
  const enc = (type, body) => {
    const id = nextId++;
    const f = new Uint8Array(CMD_HEADER + body.length);
    const dv = new DataView(f.buffer);
    f[0] = 2; f[1] = 2;
    dv.setUint32(2, body.length, true); dv.setUint32(6, id, true);
    f[10] = type; f.set(body, CMD_HEADER);
    return f;
  };
  const child = spawn(EXE, [
    "-binarymonitor", "-binarymonitoraddress", `127.0.0.1:${bport}`,
    "-remotemonitor", "-remotemonitoraddress", `127.0.0.1:${tport}`,
    "+sound", "-warp", "-console", "-silent",
    "-autostart", PRG,
  ], { stdio: ["ignore", "ignore", "ignore"] });
  let bsock;
  const onData = (chunk) => {
    const m = new Uint8Array(acc.length + chunk.length);
    m.set(acc, 0); m.set(chunk, acc.length);
    let off = 0; const dv = new DataView(m.buffer);
    while (m.length - off >= RESP_HEADER) {
      if (m[off] !== 2) { off += 1; continue; }
      const bl = dv.getUint32(off + 2, true);
      if (m.length - off < RESP_HEADER + bl) break;
      const fr = { type: m[off + 6], reqId: dv.getUint32(off + 8, true), body: m.slice(off + RESP_HEADER, off + RESP_HEADER + bl) };
      off += RESP_HEADER + bl;
      if (fr.reqId === 0xffffffff) {
        if (fr.type === 0x62 && stopWaiter) { const w = stopWaiter; stopWaiter = null; w(); }
        continue;
      }
      const w = pending.get(fr.reqId);
      if (w) { pending.delete(fr.reqId); w(fr); }
    }
    acc = m.slice(off);
  };
  const send = (type, body) => new Promise((res, rej) => {
    const f = enc(type, body);
    const id = new DataView(f.buffer).getUint32(6, true);
    pending.set(id, res);
    bsock.write(Buffer.from(f));
    setTimeout(() => { if (pending.has(id)) { pending.delete(id); rej(new Error(`timeout 0x${type.toString(16)}`)); } }, 20000);
  });
  const exit = () => bsock.write(Buffer.from(enc(0xaa, new Uint8Array(0))));
  const awaitStop = (ms = 90000) => new Promise((res, rej) => {
    stopWaiter = res;
    setTimeout(() => { if (stopWaiter) { stopWaiter = null; rej(new Error("no STOPPED")); } }, ms);
  });
  const connect = (port, attempts = 120) => new Promise((res, rej) => {
    let n = 0;
    const att = () => {
      const s = net.connect(port, "127.0.0.1");
      s.once("connect", () => res(s));
      s.once("error", () => { s.destroy(); if (++n >= attempts) rej(new Error(`connect ${port}`)); else setTimeout(att, 100); });
    };
    att();
  });
  const getPC = async () => {
    const r = await send(0x31, new Uint8Array([0]));
    const n = r.body[0] | (r.body[1] << 8);
    let p = 2;
    for (let i = 0; i < n; i++) {
      const sz = r.body[p], id = r.body[p + 1];
      if (id === 3) return r.body[p + 2] | (r.body[p + 3] << 8);
      p += 1 + sz;
    }
    return -1;
  };
  try {
    // ZERO monitor interference during boot+autostart: wait before even connecting.
    await new Promise((r) => setTimeout(r, attachDelayMs));
    bsock = await connect(bport);
    bsock.on("data", onData);
    await send(0x12, new Uint8Array([FROM & 0xff, FROM >> 8, FROM & 0xff, FROM >> 8, 1, 1, 4, 0])); // stops machine NOW
    await send(0x12, new Uint8Array([TO & 0xff, TO >> 8, TO & 0xff, TO >> 8, 1, 1, 4, 0]));
    const pcAtAttach = await getPC();
    const inPhase1 = pcAtAttach >= 0x0810 && pcAtAttach < FROM;
    const tsock = await connect(tport, 30);
    let ttext = "";
    tsock.on("data", (c) => { ttext += c.toString("latin1"); });
    const sendText = async (cmd, waitMs = 600) => {
      const mark = ttext.length;
      tsock.write(cmd + "\n");
      await new Promise((r) => setTimeout(r, waitMs));
      return ttext.slice(mark).replace(/\r/g, "");
    };
    const readAbs = async () => parseInt((await sendText("stopwatch")).match(/Stopwatch:\s*(\d+)/)?.[1] ?? "-1", 10);
    const absAttach = await readAbs(); // absolute clock (no reset issued yet in this process)
    console.error(`[${bport}] attached: PC=0x${pcAtAttach.toString(16)} abs=${absAttach} — awaiting FROM hit (~30s)…`);
    let p = awaitStop(); exit(); await p; // → FROM
    console.error(`[${bport}] FROM hit`);
    const pcFrom = await getPC();
    const absFrom = await readAbs(); // absolute cycle of the from-label arrival — decisive datum
    await sendText("stopwatch reset");
    p = awaitStop(); exit(); await p; // → TO
    const pcTo = await getPC();
    const w = await readAbs(); // delta since reset
    return { pcAtAttach, inPhase1, absAttach, absFrom, pcFrom, pcTo, w };
  } finally {
    try { bsock?.write(Buffer.from(enc(0xbb, new Uint8Array(0)))); } catch {}
    setTimeout(() => { try { child.kill("SIGKILL"); } catch {} }, 1200);
  }
}

const fmt = (r, tag) =>
  `${tag}: attachPC=0x${r.pcAtAttach.toString(16)} inPhase1=${r.inPhase1} absAttach=${r.absAttach} absFrom=${r.absFrom} from=0x${r.pcFrom.toString(16)} to=0x${r.pcTo.toString(16)} W=${r.w}`;
const r1 = await runOnce(29391, 2500);
console.log(fmt(r1, "process 1 (attach 2.5s)"));
const r2 = await runOnce(29395, 2500);
console.log(fmt(r2, "process 2 (attach 2.5s)"));
// process 3: attach at a DIFFERENT wall delay — if attach timing matters, absFrom/W change.
const r3 = await runOnce(29399, 5200);
console.log(fmt(r3, "process 3 (attach 5.2s)"));
console.log(`absFrom (absolute cycle of from-label arrival): ${r1.absFrom} / ${r2.absFrom} / ${r3.absFrom}`);
const allEq = r1.w === r2.w && r2.w === r3.w && r1.w > 0;
console.log(`NO-PRE-RUN-TOUCH DETERMINISM (W): ${r1.w} / ${r2.w} / ${r3.w} → ${allEq ? "ALL EQUAL ✓ (probe-determinism divergence came from pre-RUN monitor stops)" : "DIFFER ✗ (inherent cross-process nondeterminism)"}`);
setTimeout(() => process.exit(0), 1500);
