import { isDeepStrictEqual } from "node:util";

import type { PreparedCampaign, GeneratedCase } from "./campaign-model.js";
import { getPreparedCampaignState } from "./campaign-state.js";
import { generateCampaignCase } from "./generate-case.js";
import type { GenFunction, ScalarType } from "./generator-ir.js";
import type { ExecutionOperationResultV1 } from "./execution-contracts.js";
import {
  parseExecutionEnvelopeIrV1,
  parseExecutionInitialStateFixtureV1,
  parseExecutionObservationRequestV1,
  type ExecutionArgumentLiteralV1,
  type ExecutionEnvelopeIrV1,
  type ExecutionInitialStateFixtureV1,
  type ExecutionObservationRequestV1,
} from "./execution-envelope-contracts.js";
import type { PublishedOracleContext } from "./oracle-model.js";
import { createPublishedOracleRequest } from "./published-oracle-context.js";
import {
  createStructuredExecutionCaseDataV1,
  STRUCTURED_EXECUTION_CASE_ID_V1,
  type StructuredExecutionCaseDataV1,
} from "./structured-execution-case-data.js";

/** Compile-time marker for a runtime-backed execution-case capability. */
export const EXECUTION_CASE_BRAND: unique symbol = Symbol("execution-case");

/** Opaque authority proving a valid generated case was regenerated by its campaign. */
export interface ExecutionCaseV1 {
  /** Compile-time marker paired with module-private runtime state. */
  readonly [EXECUTION_CASE_BRAND]: true;
}

/** Frozen passive data used for rendering and identity, never execution authority. */
export interface ExecutionCaseProjectionV1 {
  /** Unchanged generated source-case digest. */
  readonly sourceCaseDigest: string;
  /** Fresh caller-owned copy of the original generated source bytes. */
  readonly sourceBytes: Uint8Array;
  /** Closed executable-envelope description. */
  readonly envelope: ExecutionEnvelopeIrV1;
  /** Logical hardware state established before entry. */
  readonly fixture: ExecutionInitialStateFixtureV1;
  /** Actual state requested after entry. */
  readonly observation: ExecutionObservationRequestV1;
}

/** Request for the one reviewed combined structured execution program. */
export interface StructuredExecutionCaseRequestV1 {
  readonly schemaVersion: 1;
  readonly kind: "structured-generated";
  readonly caseId: "case.structured.vertical-combined-v1";
}

/** Passive structured case data retained without exposing evaluator authority. */
export interface StructuredExecutionCaseProjectionV1 extends ExecutionCaseProjectionV1 {
  readonly kind: "structured-generated";
  readonly caseId: "case.structured.vertical-combined-v1";
  readonly caseDigest: `sha256:${string}`;
  readonly oracleEvaluationIdentity: `sha256:${string}`;
  readonly expectedObservation: {
    readonly kind: "direct-mmio";
    readonly address: 49152;
    readonly byteLength: 1;
    readonly value: 12;
  };
}

interface CampaignExecutionCaseState {
  readonly kind: "campaign";
  readonly campaign: PreparedCampaign;
  readonly ordinal: number;
  readonly generatedCase: GeneratedCase;
  readonly envelope: ExecutionEnvelopeIrV1;
  readonly fixture: ExecutionInitialStateFixtureV1;
}

interface StructuredExecutionCaseState {
  readonly kind: "structured-generated";
  readonly authority: StructuredExecutionCaseDataV1["authority"];
  readonly sourceBytes: Uint8Array;
  readonly envelope: ExecutionEnvelopeIrV1;
  readonly fixture: ExecutionInitialStateFixtureV1;
  readonly oracleEvaluationIdentity: `sha256:${string}`;
  readonly expectedObservation: StructuredExecutionCaseDataV1["expectedObservation"];
  readonly oracle: PublishedOracleContext;
}

type ExecutionCaseState = CampaignExecutionCaseState | StructuredExecutionCaseState;

/** Evaluator-only facts retained behind one genuine execution-case capability. */
export interface ExecutionCaseEvaluationInputV1 {
  /** Stable source identity shared with the executable envelope. */
  readonly sourceCaseDigest: string;
  /** Genuine campaign retaining deterministic seed and generation configuration. */
  readonly campaign: PreparedCampaign;
  /** Zero-based campaign ordinal regenerated into this case. */
  readonly ordinal: number;
  /** Exact generated case, including ordered external parameter bindings. */
  readonly generatedCase: GeneratedCase;
  /** Entry function selected by the executable envelope. */
  readonly entryFunction: string;
  /** Logical target fixture selected for the case. */
  readonly fixture: ExecutionInitialStateFixtureV1;
  /** Exact runtime observation requested for the case. */
  readonly observation: ExecutionObservationRequestV1;
}

const EXECUTION_CASE_STATES = new WeakMap<object, ExecutionCaseState>();
// The non-zero low nibble makes a missing modeled write observably different from its result.
const INITIAL_VIC_LOGICAL_BYTE = 0x21;

function failure<T>(path: string, message: string): ExecutionOperationResultV1<T> {
  const issues = [
    Object.freeze({ code: "invalid-evidence-input" as const, path, message }),
  ] as const;
  return Object.freeze({
    ok: false,
    issues: Object.freeze(issues),
  });
}

function success<T>(value: T): ExecutionOperationResultV1<T> {
  return Object.freeze({ ok: true, value });
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function scalarWidth(type: ScalarType | "void"): 1 | 2 | undefined {
  if (type === "boolean" || type === "byte" || type === "sbyte") return 1;
  if (type === "word" || type === "sword") return 2;
  return undefined;
}

function bindingValue(type: ScalarType, value: bigint | boolean): number | boolean | undefined {
  if (type === "boolean") return typeof value === "boolean" ? value : undefined;
  if (typeof value !== "bigint") return undefined;
  const converted = Number(value);
  return Number.isSafeInteger(converted) ? converted : undefined;
}

function deriveArguments(
  generatedCase: GeneratedCase,
  fn: GenFunction,
): readonly ExecutionArgumentLiteralV1[] | undefined {
  if (generatedCase.effectiveParameterBindings.length !== fn.parameters.length) return undefined;
  const result: ExecutionArgumentLiteralV1[] = [];
  for (let index = 0; index < fn.parameters.length; index += 1) {
    const parameter = fn.parameters[index];
    const binding = generatedCase.effectiveParameterBindings[index];
    if (
      parameter === undefined ||
      binding === undefined ||
      binding.parameterPath !== `/functions/0/parameters/${index}`
    ) {
      return undefined;
    }
    const value = bindingValue(parameter.type, binding.value);
    if (value === undefined) return undefined;
    result.push(Object.freeze({ name: parameter.name, type: parameter.type, value }));
  }
  return Object.freeze(result);
}

function memoryShape(generatedCase: GeneratedCase):
  | {
      readonly width: 1 | 2;
      readonly address: number;
      readonly writes: boolean;
    }
  | undefined {
  const choice = generatedCase.planItem.request.choice;
  if (choice.kind !== "memory") return undefined;
  const address = choice.addressForm === "computed" ? 0xd021 : 0xd020;
  const ruleId = choice.ruleId;
  if (ruleId.includes(".peekw-") || ruleId.includes(".pokew-")) {
    return { width: 2, address, writes: ruleId.includes(".pokew-") };
  }
  if (ruleId.includes(".peek-") || ruleId.includes(".poke-")) {
    return { width: 1, address, writes: ruleId.includes(".poke-") };
  }
  return undefined;
}

function deriveFixture(
  generatedCase: GeneratedCase,
): ExecutionOperationResultV1<ExecutionInitialStateFixtureV1> {
  const memory = memoryShape(generatedCase);
  const cells =
    memory === undefined
      ? []
      : Array.from({ length: memory.width }, (_unused, index) =>
          Object.freeze({
            address: memory.address + index,
            logicalValue: INITIAL_VIC_LOGICAL_BYTE,
          }),
        );
  return parseExecutionInitialStateFixtureV1({
    revision: "c64-vic-color-readback-v1",
    cells,
  });
}

function observationMatches(
  generatedCase: GeneratedCase,
  fn: GenFunction,
  observation: ExecutionObservationRequestV1,
): boolean {
  const memory = memoryShape(generatedCase);
  if (observation.kind === "scalar-bytes") {
    return fn.returnType !== "void" && scalarWidth(fn.returnType) === observation.byteLength;
  }
  return (
    fn.returnType === "void" &&
    memory?.writes === true &&
    memory.width === observation.byteLength &&
    memory.address === observation.address
  );
}

function postEntryStores(
  observation: ExecutionObservationRequestV1,
): ExecutionEnvelopeIrV1["postEntryStores"] {
  const stores =
    observation.kind === "scalar-bytes"
      ? Array.from({ length: observation.byteLength }, (_unused, index) =>
          Object.freeze({
            kind: "observation-byte" as const,
            byteIndex: index === 0 ? (0 as const) : (1 as const),
          }),
        )
      : [];
  return Object.freeze([
    ...stores,
    Object.freeze({ kind: "completion" as const, value: 165 as const }),
  ]);
}

function createFromGenerated(
  campaign: PreparedCampaign,
  ordinal: number,
  generatedCase: GeneratedCase,
  observationInput: unknown,
): ExecutionOperationResultV1<ExecutionCaseV1> {
  if (
    generatedCase.modeledCase.validity.kind !== "valid" ||
    generatedCase.modeledCase.projection.kind !== "valid"
  ) {
    return failure("/ordinal", "Only valid generated cases can become executable.");
  }
  const observation = parseExecutionObservationRequestV1(observationInput);
  if (!observation.ok) return observation;
  const fn = generatedCase.modeledCase.projection.module.functions[0];
  if (fn === undefined || !observationMatches(generatedCase, fn, observation.value)) {
    return failure("/observation", "Observation does not match the generated entry behavior.");
  }
  const argumentsValue = deriveArguments(generatedCase, fn);
  if (argumentsValue === undefined) {
    return failure("/arguments", "Generated entry arguments are incomplete or out of order.");
  }
  const envelope = parseExecutionEnvelopeIrV1({
    revision: "execution-envelope-ir-v1",
    sourceCaseDigest: generatedCase.identity.digest,
    arguments: argumentsValue,
    entryFunction: fn.name,
    observation: observation.value,
    completionInitialValue: 0,
    completionSuccessValue: 165,
    postEntryStores: postEntryStores(observation.value),
  });
  if (!envelope.ok) return envelope;
  const fixture = deriveFixture(generatedCase);
  if (!fixture.ok) return fixture;
  const capability: ExecutionCaseV1 = Object.freeze({ [EXECUTION_CASE_BRAND]: true as const });
  EXECUTION_CASE_STATES.set(
    capability,
    Object.freeze({
      kind: "campaign" as const,
      campaign,
      ordinal,
      generatedCase,
      envelope: envelope.value,
      fixture: fixture.value,
    }),
  );
  return success(capability);
}

function createStructuredExecutionCase(
  input: unknown,
): ExecutionOperationResultV1<ExecutionCaseV1> {
  if (!isRecord(input)) {
    return failure("/request", "Structured execution request must use the exact reviewed case.");
  }
  const request = input;
  if (
    Object.keys(request).length !== 3 ||
    !Object.hasOwn(request, "schemaVersion") ||
    !Object.hasOwn(request, "kind") ||
    !Object.hasOwn(request, "caseId") ||
    request.schemaVersion !== 1 ||
    request.kind !== "structured-generated" ||
    request.caseId !== STRUCTURED_EXECUTION_CASE_ID_V1
  ) {
    return failure("/request", "Structured execution request must use the exact reviewed case.");
  }
  const data = createStructuredExecutionCaseDataV1();
  if (!data.ok) return data;
  const oracle = Object.freeze({
    selectedReleaseDigest: data.value.authority.caseDigest,
  }) as PublishedOracleContext;
  const capability: ExecutionCaseV1 = Object.freeze({ [EXECUTION_CASE_BRAND]: true as const });
  EXECUTION_CASE_STATES.set(
    capability,
    Object.freeze({
      kind: "structured-generated" as const,
      authority: data.value.authority,
      sourceBytes: data.value.sourceBytes.slice(),
      envelope: data.value.envelope,
      fixture: data.value.fixture,
      oracleEvaluationIdentity: data.value.oracleEvaluationIdentity,
      expectedObservation: data.value.expectedObservation,
      oracle,
    }),
  );
  return success(capability);
}

/** Resolves the reviewed structured program into opaque execution authority. */
export function createExecutionCaseV1(
  request: StructuredExecutionCaseRequestV1,
): ExecutionOperationResultV1<ExecutionCaseV1>;

/** Regenerates one valid campaign ordinal and closes it into opaque execution authority. */
export function createExecutionCaseV1(
  campaign: PreparedCampaign,
  ordinal: number,
  observation: ExecutionObservationRequestV1,
): ExecutionOperationResultV1<ExecutionCaseV1>;

export function createExecutionCaseV1(
  campaignOrRequest: PreparedCampaign | StructuredExecutionCaseRequestV1,
  ordinal?: number,
  observation?: ExecutionObservationRequestV1,
): ExecutionOperationResultV1<ExecutionCaseV1> {
  if (ordinal === undefined && observation === undefined) {
    return createStructuredExecutionCase(campaignOrRequest);
  }
  if (typeof ordinal !== "number" || !Number.isSafeInteger(ordinal) || ordinal < 0) {
    return failure("/ordinal", "Execution ordinal must be a non-negative safe integer.");
  }
  if (observation === undefined) {
    return failure("/observation", "Execution observation is required.");
  }
  const generated = generateCampaignCase(campaignOrRequest as PreparedCampaign, ordinal);
  return generated.ok
    ? createFromGenerated(
        campaignOrRequest as PreparedCampaign,
        ordinal,
        generated.value,
        observation,
      )
    : failure("/campaign", "Campaign or ordinal is not genuine and replayable.");
}

/** Resolves passive historical envelope bytes through their named genuine campaign. */
export function resolveExecutionEnvelopeReplayV1(
  campaign: PreparedCampaign,
  envelopeInput: ExecutionEnvelopeIrV1,
): ExecutionOperationResultV1<ExecutionCaseV1> {
  const envelope = parseExecutionEnvelopeIrV1(envelopeInput);
  if (!envelope.ok) return envelope;
  const campaignState = getPreparedCampaignState(campaign);
  if (campaignState === undefined) {
    return failure("/campaign", "Historical campaign is invalid.");
  }
  const total = campaignState.configuration.caseCount;
  for (let ordinal = 0; ordinal < total; ordinal += 1) {
    const generated = generateCampaignCase(campaign, ordinal);
    if (!generated.ok || generated.value.identity.digest !== envelope.value.sourceCaseDigest) {
      continue;
    }
    const resolved = createFromGenerated(
      campaign,
      ordinal,
      generated.value,
      envelope.value.observation,
    );
    if (!resolved.ok) return resolved;
    const state = getExecutionCaseStateV1(resolved.value);
    return state !== undefined && isDeepStrictEqual(state.envelope, envelope.value)
      ? resolved
      : failure("/envelope", "Historical envelope does not match regenerated campaign data.");
  }
  return failure(
    "/envelope/sourceCaseDigest",
    "Historical source case is absent from the campaign.",
  );
}

/** Returns an isolated frozen passive projection for a genuine execution capability. */
export function getExecutionCaseProjectionV1(
  executionCase: ExecutionCaseV1,
): ExecutionOperationResultV1<ExecutionCaseProjectionV1> {
  const state = getExecutionCaseStateV1(executionCase);
  if (state === undefined) return failure("/executionCase", "Execution case authority is invalid.");
  if (state.kind === "structured-generated") {
    return success(
      Object.freeze({
        sourceCaseDigest: state.authority.caseDigest,
        sourceBytes: state.sourceBytes.slice(),
        envelope: state.envelope,
        fixture: state.fixture,
        observation: state.envelope.observation,
      }),
    );
  }
  return success(
    Object.freeze({
      sourceCaseDigest: state.generatedCase.identity.digest,
      sourceBytes: state.generatedCase.sourceBytes.slice(),
      envelope: state.envelope,
      fixture: state.fixture,
      observation: state.envelope.observation,
    }),
  );
}

/** Returns the fresh passive projection retained by a genuine structured execution case. */
export function getStructuredExecutionCaseProjectionV1(
  executionCase: ExecutionCaseV1,
): ExecutionOperationResultV1<StructuredExecutionCaseProjectionV1> {
  const state = getExecutionCaseStateV1(executionCase);
  if (state?.kind !== "structured-generated") {
    return failure("/executionCase", "Structured execution case authority is invalid.");
  }
  return success(
    Object.freeze({
      kind: "structured-generated" as const,
      caseId: STRUCTURED_EXECUTION_CASE_ID_V1,
      caseDigest: state.authority.caseDigest,
      sourceCaseDigest: state.authority.caseDigest,
      sourceBytes: state.sourceBytes.slice(),
      envelope: state.envelope,
      fixture: state.fixture,
      observation: state.envelope.observation,
      oracleEvaluationIdentity: state.oracleEvaluationIdentity,
      expectedObservation: state.expectedObservation,
    }),
  );
}

/** Returns only the opaque oracle token paired with a genuine structured execution case. */
export function getStructuredExecutionOracleContextV1(
  executionCase: ExecutionCaseV1,
): ExecutionOperationResultV1<PublishedOracleContext> {
  const state = getExecutionCaseStateV1(executionCase);
  return state?.kind === "structured-generated"
    ? success(state.oracle)
    : failure("/executionCase", "Structured execution case authority is invalid.");
}

/** Authenticates an oracle only when it belongs to the exact execution case. */
export function isExecutionCaseOraclePairV1(
  executionCase: ExecutionCaseV1,
  oracle: PublishedOracleContext,
): boolean {
  const state = getExecutionCaseStateV1(executionCase);
  if (state === undefined) return false;
  if (state.kind === "structured-generated") return state.oracle === oracle;
  const probe = createPublishedOracleRequest(oracle, {});
  return !probe.ok && probe.diagnostics[0]?.code !== "oracle.authority.missing";
}

/**
 * Resolves evaluator-only state for a genuine execution case.
 *
 * This package-internal seam keeps generated semantics behind the same opaque capability used by
 * rendering and execution. It is intentionally not re-exported from the package entry point.
 */
export function getExecutionCaseEvaluationInputV1(
  executionCase: ExecutionCaseV1,
): ExecutionCaseEvaluationInputV1 | undefined {
  const state = getExecutionCaseStateV1(executionCase);
  if (state === undefined || state.kind !== "campaign") return undefined;
  return Object.freeze({
    sourceCaseDigest: state.generatedCase.identity.digest,
    campaign: state.campaign,
    ordinal: state.ordinal,
    generatedCase: state.generatedCase,
    entryFunction: state.envelope.entryFunction,
    fixture: state.fixture,
    observation: state.envelope.observation,
  });
}

function getExecutionCaseStateV1(executionCase: ExecutionCaseV1): ExecutionCaseState | undefined {
  if (typeof executionCase !== "object" || executionCase === null) return undefined;
  return EXECUTION_CASE_STATES.get(executionCase);
}
