import type { GeneratedCandidateRevision } from "./modeled-candidate-revisions.generated.js";

const ORACLE_CANDIDATE_DEPENDENCY_PATHS = Object.freeze([
  "packages/readiness/src/authority-loader.ts",
  "packages/readiness/src/authority-order.ts",
  "packages/readiness/src/binding-model.ts",
  "packages/readiness/src/binding-validator.ts",
  "packages/readiness/src/blocking-reasons.ts",
  "packages/readiness/src/boundary-variants.ts",
  "packages/readiness/src/campaign-collision.ts",
  "packages/readiness/src/campaign-dependencies.ts",
  "packages/readiness/src/campaign-model.ts",
  "packages/readiness/src/campaign-plan-item-snapshot.ts",
  "packages/readiness/src/campaign-plan-item.ts",
  "packages/readiness/src/campaign-state.ts",
  "packages/readiness/src/campaign.ts",
  "packages/readiness/src/canonical-identity.ts",
  "packages/readiness/src/case-generator.ts",
  "packages/readiness/src/case-identity.ts",
  "packages/readiness/src/citation-identity.ts",
  "packages/readiness/src/conflict-validator.ts",
  "packages/readiness/src/declaration-validator.ts",
  "packages/readiness/src/deterministic-choice.ts",
  "packages/readiness/src/diagnostics.ts",
  "packages/readiness/src/expression-renderer.ts",
  "packages/readiness/src/fragment-model.ts",
  "packages/readiness/src/fragmenter.ts",
  "packages/readiness/src/generate-case.ts",
  "packages/readiness/src/generation-budget.ts",
  "packages/readiness/src/generator-ir-validator.ts",
  "packages/readiness/src/generator-ir.ts",
  "packages/readiness/src/identity-collision-registry.ts",
  "packages/readiness/src/identity-ledger.ts",
  "packages/readiness/src/implementation-revision.ts",
  "packages/readiness/src/invalid-roundtrip-projection.ts",
  "packages/readiness/src/json-input.ts",
  "packages/readiness/src/ledger-validator.ts",
  "packages/readiness/src/limits.ts",
  "packages/readiness/src/model-registry-model.ts",
  "packages/readiness/src/model.ts",
  "packages/readiness/src/modeled-candidate-bindings.ts",
  "packages/readiness/src/modeled-candidate-revisions.generated.ts",
  "packages/readiness/src/modeled-case-builder.ts",
  "packages/readiness/src/modeled-construction-templates.ts",
  "packages/readiness/src/modeled-generator-facts.ts",
  "packages/readiness/src/modeled-generator-model.ts",
  "packages/readiness/src/modeled-generator-suite.ts",
  "packages/readiness/src/modeled-generators.ts",
  "packages/readiness/src/modeled-operation-registry.ts",
  "packages/readiness/src/oracle-authority-policy.ts",
  "packages/readiness/src/oracle-binding-rejection.ts",
  "packages/readiness/src/oracle-budget.ts",
  "packages/readiness/src/oracle-candidate-adapter.ts",
  "packages/readiness/src/oracle-candidate-bindings.ts",
  "packages/readiness/src/oracle-canonical-identity.ts",
  "packages/readiness/src/oracle-compiler-result-candidate.ts",
  "packages/readiness/src/oracle-conformance-v1.ts",
  "packages/readiness/src/oracle-content-identity.ts",
  "packages/readiness/src/oracle-diagnostic-input.ts",
  "packages/readiness/src/oracle-emitted-program-candidate.ts",
  "packages/readiness/src/oracle-evaluation-collision.ts",
  "packages/readiness/src/oracle-evaluation-identity.ts",
  "packages/readiness/src/oracle-evaluator.ts",
  "packages/readiness/src/oracle-frontend-result-candidate.ts",
  "packages/readiness/src/oracle-handlers.ts",
  "packages/readiness/src/oracle-input.ts",
  "packages/readiness/src/oracle-memory.ts",
  "packages/readiness/src/oracle-model.ts",
  "packages/readiness/src/oracle-operations.ts",
  "packages/readiness/src/oracle-provenance.ts",
  "packages/readiness/src/oracle-request.ts",
  "packages/readiness/src/oracle-routing.ts",
  "packages/readiness/src/oracle-runtime-state-candidate.ts",
  "packages/readiness/src/oracle-semantic-closure.ts",
  "packages/readiness/src/oracle-semantic-relations-candidate.ts",
  "packages/readiness/src/oracle-state.ts",
  "packages/readiness/src/oracle-suite.ts",
  "packages/readiness/src/oracle-values.ts",
  "packages/readiness/src/programmatic-input.ts",
  "packages/readiness/src/publication-binding-lookup.ts",
  "packages/readiness/src/publication-candidates.ts",
  "packages/readiness/src/publication-conformance-v1.ts",
  "packages/readiness/src/publication-filesystem.ts",
  "packages/readiness/src/publication-model.ts",
  "packages/readiness/src/publication-resolver.ts",
  "packages/readiness/src/publication-review.ts",
  "packages/readiness/src/published-oracle-context.ts",
  "packages/readiness/src/published-replay-authority.generated.ts",
  "packages/readiness/src/published-replay-authority.ts",
  "packages/readiness/src/replay-envelope-normalizer.ts",
  "packages/readiness/src/replay-input-model.ts",
  "packages/readiness/src/replay-input.ts",
  "packages/readiness/src/replay-json-inspector.ts",
  "packages/readiness/src/replay-target.ts",
  "packages/readiness/src/replay.ts",
  "packages/readiness/src/review-digests.ts",
  "packages/readiness/src/review-evidence.ts",
  "packages/readiness/src/revision-registry.ts",
  "packages/readiness/src/roundtrip-model.ts",
  "packages/readiness/src/roundtrip-parser.ts",
  "packages/readiness/src/roundtrip-tokenizer.ts",
  "packages/readiness/src/roundtrip-validator.ts",
  "packages/readiness/src/rule-graph.ts",
  "packages/readiness/src/rule-model-input.ts",
  "packages/readiness/src/rule-model-registry.ts",
  "packages/readiness/src/rule-model-validator.ts",
  "packages/readiness/src/schema-validator.ts",
  "packages/readiness/src/semantic-relation-analysis.ts",
  "packages/readiness/src/semantic-relation-compare.ts",
  "packages/readiness/src/semantic-relation-conformance.ts",
  "packages/readiness/src/semantic-relation-freeze.ts",
  "packages/readiness/src/semantic-relation-input.ts",
  "packages/readiness/src/semantic-relation-model.ts",
  "packages/readiness/src/semantic-relation-transform.ts",
  "packages/readiness/src/semantic-relations.ts",
  "packages/readiness/src/semantic-validator.ts",
  "packages/readiness/src/source-bytes.ts",
  "packages/readiness/src/source-renderer.ts",
  "packages/readiness/src/source-repository.ts",
  "packages/readiness/src/strict-json.ts",
  "packages/readiness/src/versioning.ts",
  "readiness/oracles/binding-rejections-v1.json",
  "readiness/oracles/diagnostic-oracle-v1.json",
]);

/** Generated dependency authority for the compiler-result candidate. */
export const ORACLE_COMPILER_RESULT_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-compiler-result-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:d823e0265837783382a1d54ddbc6fc4056f55f8a19398de071c37b493ad48811",
});

/** Generated dependency authority for the emitted-program candidate. */
export const ORACLE_EMITTED_PROGRAM_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-emitted-program-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:eee7c4bffb4c1685895fc6ffb1b14f5cfcb1bf802dc2ce30333508aa65c47744",
});

/** Generated dependency authority for the frontend-result candidate. */
export const ORACLE_FRONTEND_RESULT_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-frontend-result-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:7575f6a46fd27a082b0c944d7d7283a68ba11c04365f41dd787ee52b6f1dd6ac",
});

/** Generated dependency authority for the runtime-state candidate. */
export const ORACLE_RUNTIME_STATE_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-runtime-state-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:d1a2bc69559aa47563214a26a2a2787eee211a477c210008d217ce57cf6bfa70",
});

/** Generated dependency authority for the semantic-relation candidate. */
export const ORACLE_SEMANTIC_RELATIONS_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-semantic-relations-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:0dfad08b093e7f43e56e028de2bddc5358bd195b10d3698b9b6ba514a6d5a9e3",
});
