import type { GeneratedCandidateRevision } from "./modeled-candidate-revisions.generated.js";

const ORACLE_CANDIDATE_DEPENDENCY_PATHS = Object.freeze([
  "packages/readiness/src/authority-loader.ts",
  "packages/readiness/src/authority-order.ts",
  "packages/readiness/src/binding-model.ts",
  "packages/readiness/src/binding-validator.ts",
  "packages/readiness/src/blocking-reasons.ts",
  "packages/readiness/src/boundary-variants.ts",
  "packages/readiness/src/campaign-collision.ts",
  "packages/readiness/src/campaign-dependencies.ts",
  "packages/readiness/src/campaign-model.ts",
  "packages/readiness/src/campaign-plan-item-snapshot.ts",
  "packages/readiness/src/campaign-plan-item.ts",
  "packages/readiness/src/campaign-state.ts",
  "packages/readiness/src/campaign.ts",
  "packages/readiness/src/canonical-identity.ts",
  "packages/readiness/src/case-generator.ts",
  "packages/readiness/src/case-identity.ts",
  "packages/readiness/src/citation-identity.ts",
  "packages/readiness/src/compatible-publication-model.ts",
  "packages/readiness/src/conflict-validator.ts",
  "packages/readiness/src/declaration-validator.ts",
  "packages/readiness/src/deterministic-choice.ts",
  "packages/readiness/src/diagnostics.ts",
  "packages/readiness/src/embed-case-fixtures.ts",
  "packages/readiness/src/execution-contracts.ts",
  "packages/readiness/src/execution-envelope-contracts.ts",
  "packages/readiness/src/execution-validation.ts",
  "packages/readiness/src/expression-renderer.ts",
  "packages/readiness/src/first-vertical-publication.ts",
  "packages/readiness/src/fragment-model.ts",
  "packages/readiness/src/fragmenter.ts",
  "packages/readiness/src/generate-case.ts",
  "packages/readiness/src/generation-budget.ts",
  "packages/readiness/src/generator-input-inspection.ts",
  "packages/readiness/src/generator-ir-expression-parser.ts",
  "packages/readiness/src/generator-ir-legacy-semantics.ts",
  "packages/readiness/src/generator-ir-parser-common.ts",
  "packages/readiness/src/generator-ir-validator.ts",
  "packages/readiness/src/generator-ir.ts",
  "packages/readiness/src/identity-collision-registry.ts",
  "packages/readiness/src/identity-ledger.ts",
  "packages/readiness/src/implementation-revision.ts",
  "packages/readiness/src/invalid-roundtrip-projection.ts",
  "packages/readiness/src/json-input.ts",
  "packages/readiness/src/ledger-validator.ts",
  "packages/readiness/src/limits.ts",
  "packages/readiness/src/model-registry-model.ts",
  "packages/readiness/src/model.ts",
  "packages/readiness/src/modeled-candidate-bindings.ts",
  "packages/readiness/src/modeled-candidate-revisions.generated.ts",
  "packages/readiness/src/modeled-case-builder.ts",
  "packages/readiness/src/modeled-construction-templates.ts",
  "packages/readiness/src/modeled-generator-facts.ts",
  "packages/readiness/src/modeled-generator-model.ts",
  "packages/readiness/src/modeled-generator-suite.ts",
  "packages/readiness/src/modeled-generators.ts",
  "packages/readiness/src/modeled-operation-registry.ts",
  "packages/readiness/src/oracle-authority-policy.ts",
  "packages/readiness/src/oracle-binding-rejection.ts",
  "packages/readiness/src/oracle-budget.ts",
  "packages/readiness/src/oracle-candidate-adapter.ts",
  "packages/readiness/src/oracle-candidate-bindings.ts",
  "packages/readiness/src/oracle-canonical-identity.ts",
  "packages/readiness/src/oracle-compiler-result-candidate.ts",
  "packages/readiness/src/oracle-conformance-v1.ts",
  "packages/readiness/src/oracle-content-identity.ts",
  "packages/readiness/src/oracle-diagnostic-input.ts",
  "packages/readiness/src/oracle-emitted-program-candidate.ts",
  "packages/readiness/src/oracle-evaluation-collision.ts",
  "packages/readiness/src/oracle-evaluation-identity.ts",
  "packages/readiness/src/oracle-evaluator.ts",
  "packages/readiness/src/oracle-frontend-result-candidate.ts",
  "packages/readiness/src/oracle-handlers.ts",
  "packages/readiness/src/oracle-input.ts",
  "packages/readiness/src/oracle-memory.ts",
  "packages/readiness/src/oracle-model.ts",
  "packages/readiness/src/oracle-operations.ts",
  "packages/readiness/src/oracle-provenance.ts",
  "packages/readiness/src/oracle-request.ts",
  "packages/readiness/src/oracle-routing.ts",
  "packages/readiness/src/oracle-runtime-state-candidate.ts",
  "packages/readiness/src/oracle-semantic-closure.ts",
  "packages/readiness/src/oracle-semantic-relations-candidate.ts",
  "packages/readiness/src/oracle-state.ts",
  "packages/readiness/src/oracle-suite.ts",
  "packages/readiness/src/oracle-values.ts",
  "packages/readiness/src/programmatic-input.ts",
  "packages/readiness/src/publication-authority-loader.ts",
  "packages/readiness/src/publication-authority-revision.generated.ts",
  "packages/readiness/src/publication-binding-lookup.ts",
  "packages/readiness/src/publication-candidates.ts",
  "packages/readiness/src/publication-conformance-v1.ts",
  "packages/readiness/src/publication-filesystem.ts",
  "packages/readiness/src/publication-implementation-authority.ts",
  "packages/readiness/src/publication-model.ts",
  "packages/readiness/src/publication-release-resolver.ts",
  "packages/readiness/src/publication-resolver-support.ts",
  "packages/readiness/src/publication-resolver.ts",
  "packages/readiness/src/publication-review.ts",
  "packages/readiness/src/publication-snapshot-state.ts",
  "packages/readiness/src/published-oracle-campaign.ts",
  "packages/readiness/src/published-oracle-context.ts",
  "packages/readiness/src/published-oracle-evaluation.ts",
  "packages/readiness/src/published-oracle-state.ts",
  "packages/readiness/src/published-replay-authority.generated.ts",
  "packages/readiness/src/published-replay-authority.ts",
  "packages/readiness/src/replay-envelope-normalizer.ts",
  "packages/readiness/src/replay-input-model.ts",
  "packages/readiness/src/replay-input.ts",
  "packages/readiness/src/replay-json-inspector.ts",
  "packages/readiness/src/replay-target.ts",
  "packages/readiness/src/replay.ts",
  "packages/readiness/src/review-digests.ts",
  "packages/readiness/src/review-evidence.ts",
  "packages/readiness/src/revision-registry.ts",
  "packages/readiness/src/roundtrip-model.ts",
  "packages/readiness/src/roundtrip-parser.ts",
  "packages/readiness/src/roundtrip-tokenizer.ts",
  "packages/readiness/src/roundtrip-validator.ts",
  "packages/readiness/src/rule-family-executable-authority.ts",
  "packages/readiness/src/rule-family-handler-catalog.ts",
  "packages/readiness/src/rule-family-inventory.ts",
  "packages/readiness/src/rule-family-model-input.ts",
  "packages/readiness/src/rule-family-model-validation.ts",
  "packages/readiness/src/rule-family-model.ts",
  "packages/readiness/src/rule-family-publication-diagnostics.ts",
  "packages/readiness/src/rule-family-publication-record.ts",
  "packages/readiness/src/rule-family-publication-review.ts",
  "packages/readiness/src/rule-family-publication-validation.ts",
  "packages/readiness/src/rule-graph.ts",
  "packages/readiness/src/rule-model-input.ts",
  "packages/readiness/src/rule-model-migration.ts",
  "packages/readiness/src/rule-model-registry.ts",
  "packages/readiness/src/rule-model-validator.ts",
  "packages/readiness/src/rule-model-version.ts",
  "packages/readiness/src/schema-validator.ts",
  "packages/readiness/src/semantic-relation-analysis.ts",
  "packages/readiness/src/semantic-relation-compare.ts",
  "packages/readiness/src/semantic-relation-conformance.ts",
  "packages/readiness/src/semantic-relation-freeze.ts",
  "packages/readiness/src/semantic-relation-input.ts",
  "packages/readiness/src/semantic-relation-model.ts",
  "packages/readiness/src/semantic-relation-transform.ts",
  "packages/readiness/src/semantic-relations.ts",
  "packages/readiness/src/semantic-validator.ts",
  "packages/readiness/src/source-bytes.ts",
  "packages/readiness/src/source-renderer.ts",
  "packages/readiness/src/source-repository.ts",
  "packages/readiness/src/strict-json.ts",
  "packages/readiness/src/structured-case-families.ts",
  "packages/readiness/src/structured-case-registry.ts",
  "packages/readiness/src/structured-execution-case-data.ts",
  "packages/readiness/src/structured-execution-exemplar.ts",
  "packages/readiness/src/structured-ir-call-graph.ts",
  "packages/readiness/src/structured-ir-diagnostics.ts",
  "packages/readiness/src/structured-ir-input.ts",
  "packages/readiness/src/structured-ir-semantic-diagnostics.ts",
  "packages/readiness/src/structured-ir-semantic-types.ts",
  "packages/readiness/src/structured-ir-semantics.ts",
  "packages/readiness/src/structured-ir-usage.ts",
  "packages/readiness/src/structured-ir-validation.ts",
  "packages/readiness/src/structured-oracle-evaluator.ts",
  "packages/readiness/src/structured-oracle-runtime.ts",
  "packages/readiness/src/structured-source-renderer.ts",
  "packages/readiness/src/terminal-rule-disposition.ts",
  "packages/readiness/src/versioning.ts",
  "readiness/oracles/binding-rejections-v1.json",
  "readiness/oracles/diagnostic-oracle-v1.json",
]);

/** Generated dependency authority for the compiler-result candidate. */
export const ORACLE_COMPILER_RESULT_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-compiler-result-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:2c24e877cc1bb4a2488590f2c63d82850fb4699b3805ca84bcdd3423179b4301",
});

/** Generated dependency authority for the emitted-program candidate. */
export const ORACLE_EMITTED_PROGRAM_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-emitted-program-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:a0771c138f14534dbfc4cd3f9d3e7a215200d852495b541bd1a8dca47ba64737",
});

/** Generated dependency authority for the frontend-result candidate. */
export const ORACLE_FRONTEND_RESULT_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-frontend-result-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:c9017e98ad24c09d1c623a528047d2b4b7eb02a6cfddc0af7898d9663d150c7a",
});

/** Generated dependency authority for the runtime-state candidate. */
export const ORACLE_RUNTIME_STATE_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-runtime-state-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:135fe2198a7461f80dc6cbfe5706c12d2bdffb003c1d32de7a9027b66f599472",
});

/** Generated dependency authority for the semantic-relation candidate. */
export const ORACLE_SEMANTIC_RELATIONS_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/oracle-semantic-relations-candidate.ts",
  dependencyPaths: ORACLE_CANDIDATE_DEPENDENCY_PATHS,
  claimedRevision: "sha256:59795d1c258e3e27ad0c58b2acf4156e638803502731e30e9fe25ddc31ed2e5c",
});
