import type { GeneratedCandidateRevision } from "./modeled-candidate-revisions.generated.js";

/**
 * Generated content authority for compatible publication preparation, capability use and commit.
 */
export const COMPATIBLE_PUBLICATION_AUTHORITY_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/binding-publication.ts",
  dependencyPaths: Object.freeze([
    "packages/readiness/package.json",
    "packages/readiness/src/authority-loader.ts",
    "packages/readiness/src/authority-order.ts",
    "packages/readiness/src/binding-model.ts",
    "packages/readiness/src/binding-publication.ts",
    "packages/readiness/src/binding-validator.ts",
    "packages/readiness/src/canonical-identity.ts",
    "packages/readiness/src/compatible-publication-model.ts",
    "packages/readiness/src/declaration-validator.ts",
    "packages/readiness/src/diagnostics.ts",
    "packages/readiness/src/fragment-model.ts",
    "packages/readiness/src/generation-lock.ts",
    "packages/readiness/src/implementation-revision.ts",
    "packages/readiness/src/index.ts",
    "packages/readiness/src/json-input.ts",
    "packages/readiness/src/ledger-validator.ts",
    "packages/readiness/src/limits.ts",
    "packages/readiness/src/model-registry-model.ts",
    "packages/readiness/src/model.ts",
    "packages/readiness/src/projection.ts",
    "packages/readiness/src/publication-authority-loader.ts",
    "packages/readiness/src/publication-binding-lookup.ts",
    "packages/readiness/src/publication-candidates.ts",
    "packages/readiness/src/publication-conformance-v1.ts",
    "packages/readiness/src/publication-filesystem.ts",
    "packages/readiness/src/publication-implementation-authority.ts",
    "packages/readiness/src/publication-model.ts",
    "packages/readiness/src/publication-pointer.ts",
    "packages/readiness/src/publication-resolver.ts",
    "packages/readiness/src/publication-review.ts",
    "packages/readiness/src/published-diagnostic-case.ts",
    "packages/readiness/src/published-oracle-context.ts",
    "packages/readiness/src/published-oracle.ts",
    "packages/readiness/src/published-replay-authority.ts",
    "packages/readiness/src/review-digests.ts",
    "packages/readiness/src/review-evidence.ts",
    "packages/readiness/src/rule-model-input.ts",
    "packages/readiness/src/schema-validator.ts",
    "packages/readiness/src/strict-json.ts",
    "packages/readiness/src/versioning.ts",
  ]),
  claimedRevision: "sha256:b121d2a801f0c607d6dc2280dc0b1fc257ddec901bd1ff6ef63c06ea9217a7bc",
});
