import type { GeneratedCandidateRevision } from "./modeled-candidate-revisions.generated.js";

/** Generated dependency authority for deterministic published source rendering. */
export const PUBLISHED_RENDERER_REVISION: GeneratedCandidateRevision = Object.freeze({
  entryPath: "packages/readiness/src/case-generator.ts",
  dependencyPaths: Object.freeze([
    "packages/readiness/src/binding-model.ts",
    "packages/readiness/src/campaign-model.ts",
    "packages/readiness/src/canonical-identity.ts",
    "packages/readiness/src/case-generator.ts",
    "packages/readiness/src/case-identity.ts",
    "packages/readiness/src/expression-renderer.ts",
    "packages/readiness/src/fragment-model.ts",
    "packages/readiness/src/generation-budget.ts",
    "packages/readiness/src/generator-input-inspection.ts",
    "packages/readiness/src/generator-ir-expression-parser.ts",
    "packages/readiness/src/generator-ir-legacy-semantics.ts",
    "packages/readiness/src/generator-ir-parser-common.ts",
    "packages/readiness/src/generator-ir-validator.ts",
    "packages/readiness/src/generator-ir.ts",
    "packages/readiness/src/identity-collision-registry.ts",
    "packages/readiness/src/implementation-revision.ts",
    "packages/readiness/src/invalid-roundtrip-projection.ts",
    "packages/readiness/src/limits.ts",
    "packages/readiness/src/model-registry-model.ts",
    "packages/readiness/src/model.ts",
    "packages/readiness/src/modeled-generator-model.ts",
    "packages/readiness/src/programmatic-input.ts",
    "packages/readiness/src/roundtrip-model.ts",
    "packages/readiness/src/roundtrip-parser.ts",
    "packages/readiness/src/roundtrip-tokenizer.ts",
    "packages/readiness/src/roundtrip-validator.ts",
    "packages/readiness/src/rule-model-registry.ts",
    "packages/readiness/src/source-renderer.ts",
    "packages/readiness/src/structured-ir-call-graph.ts",
    "packages/readiness/src/structured-ir-diagnostics.ts",
    "packages/readiness/src/structured-ir-semantic-diagnostics.ts",
    "packages/readiness/src/structured-ir-semantic-types.ts",
    "packages/readiness/src/structured-ir-semantics.ts",
    "packages/readiness/src/structured-source-renderer.ts",
  ]),
  claimedRevision: "sha256:795fe4916e2d97e8bba965a7f1b7c526036827476be617c918c9648178be64bd",
});
