/**
 * ASM-IL Builder
 *
 * Fluent API for constructing ASM-IL output.
 * Provides convenient methods for adding instructions, labels,
 * directives, and other elements to the assembly output.
 *
 * @module codegen/asm-il/builder
 */

import {
  AsmAddressingMode,
  AsmILElement,
  AsmILProgram,
  AsmILSection,
  createAsmILProgram,
  createBlankElement,
  createCommentElement,
  createDataElement,
  createDirectiveElement,
  createInstructionElement,
  createLabelElement,
  createSection,
} from './types.js';

// ============================================================================
// Builder Class
// ============================================================================

/**
 * Builder for constructing ASM-IL programs.
 *
 * Provides a fluent API for adding assembly elements.
 * Manages sections and tracks statistics.
 *
 * @example
 * ```typescript
 * const builder = new AsmILBuilder('main');
 *
 * builder
 *   .section('header')
 *   .comment('Generated by Blend65')
 *   .directive('*=', 0x0801)
 *   .section('code')
 *   .label('main')
 *   .lda(0xFF, 'immediate')
 *   .sta(0xD020, 'absolute')
 *   .rts();
 *
 * const program = builder.build();
 * ```
 */
export class AsmILBuilder {
  /** The program being built */
  protected program: AsmILProgram;

  /** Current section being built */
  protected currentSection: AsmILSection;

  /** Instruction count */
  protected instructionCount: number = 0;

  /** Label count */
  protected labelCount: number = 0;

  /** Estimated bytes */
  protected estimatedBytes: number = 0;

  /** Estimated cycles */
  protected estimatedCycles: number = 0;

  /**
   * Creates a new ASM-IL builder.
   *
   * @param moduleName - Name of the module being generated
   */
  constructor(moduleName: string) {
    this.program = createAsmILProgram(moduleName);
    this.currentSection = createSection('default');
    this.program.sections.push(this.currentSection);
  }

  // ==========================================================================
  // Section Management
  // ==========================================================================

  /**
   * Starts a new section.
   *
   * @param name - Section name
   * @returns this for chaining
   */
  public section(name: string): this {
    // Check if section already exists
    const existing = this.program.sections.find((s) => s.name === name);
    if (existing) {
      this.currentSection = existing;
    } else {
      this.currentSection = createSection(name);
      this.program.sections.push(this.currentSection);
    }
    return this;
  }

  /**
   * Gets the current section name.
   */
  public getCurrentSectionName(): string {
    return this.currentSection.name;
  }

  // ==========================================================================
  // Basic Elements
  // ==========================================================================

  /**
   * Adds a comment line.
   *
   * @param text - Comment text
   * @returns this for chaining
   */
  public comment(text: string): this {
    this.currentSection.elements.push(createCommentElement(text));
    return this;
  }

  /**
   * Adds a blank line.
   *
   * @returns this for chaining
   */
  public blank(): this {
    this.currentSection.elements.push(createBlankElement());
    return this;
  }

  /**
   * Adds a label.
   *
   * @param name - Label name
   * @param isLocal - Whether this is a local label (default: false)
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public label(name: string, isLocal: boolean = false, comment?: string): this {
    this.currentSection.elements.push(createLabelElement(name, isLocal, comment));
    this.labelCount++;
    return this;
  }

  /**
   * Adds a directive.
   *
   * @param directive - Directive name (e.g., '*=', '!byte')
   * @param value - Single value
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public directive(
    directive: string,
    value?: number | string,
    comment?: string
  ): this {
    this.currentSection.elements.push(
      createDirectiveElement(directive, value, undefined, comment)
    );
    return this;
  }

  /**
   * Adds a data directive with multiple values.
   *
   * @param directive - Directive name (e.g., '!byte', '!word')
   * @param values - Array of values
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public dataDirective(
    directive: string,
    values: number[],
    comment?: string
  ): this {
    this.currentSection.elements.push(
      createDirectiveElement(directive, undefined, values, comment)
    );
    this.estimatedBytes += values.length * (directive === '!word' ? 2 : 1);
    return this;
  }

  /**
   * Adds raw data bytes.
   *
   * @param bytes - Byte values
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public data(bytes: number[], comment?: string): this {
    this.currentSection.elements.push(createDataElement(bytes, comment));
    this.estimatedBytes += bytes.length;
    return this;
  }

  // ==========================================================================
  // Raw Instruction Addition
  // ==========================================================================

  /**
   * Adds a raw instruction element.
   *
   * @param mnemonic - Instruction mnemonic
   * @param mode - Addressing mode
   * @param operand - Operand value
   * @param labelOperand - Label operand
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public instruction(
    mnemonic: string,
    mode: AsmAddressingMode,
    operand?: number,
    labelOperand?: string,
    comment?: string
  ): this {
    this.currentSection.elements.push(
      createInstructionElement(mnemonic, mode, operand, labelOperand, comment)
    );
    this.instructionCount++;
    this.addCostEstimate(mnemonic, mode);
    return this;
  }

  // ==========================================================================
  // Load Instructions
  // ==========================================================================

  /**
   * LDA - Load Accumulator.
   */
  public lda(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('LDA', asmMode, operand, undefined, comment);
  }

  /**
   * LDX - Load X Register.
   */
  public ldx(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageY' | 'absolute' | 'absoluteY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('LDX', asmMode, operand, undefined, comment);
  }

  /**
   * LDY - Load Y Register.
   */
  public ldy(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('LDY', asmMode, operand, undefined, comment);
  }

  // ==========================================================================
  // Store Instructions
  // ==========================================================================

  /**
   * STA - Store Accumulator.
   */
  public sta(
    operand: number,
    mode: 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('STA', asmMode, operand, undefined, comment);
  }

  /**
   * STX - Store X Register.
   */
  public stx(
    operand: number,
    mode: 'zeroPage' | 'zeroPageY' | 'absolute',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('STX', asmMode, operand, undefined, comment);
  }

  /**
   * STY - Store Y Register.
   */
  public sty(
    operand: number,
    mode: 'zeroPage' | 'zeroPageX' | 'absolute',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('STY', asmMode, operand, undefined, comment);
  }

  // ==========================================================================
  // Arithmetic Instructions
  // ==========================================================================

  /**
   * ADC - Add with Carry.
   */
  public adc(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('ADC', asmMode, operand, undefined, comment);
  }

  /**
   * SBC - Subtract with Carry.
   */
  public sbc(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('SBC', asmMode, operand, undefined, comment);
  }

  /**
   * INC - Increment Memory.
   */
  public inc(
    operand: number,
    mode: 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('INC', asmMode, operand, undefined, comment);
  }

  /**
   * DEC - Decrement Memory.
   */
  public dec(
    operand: number,
    mode: 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('DEC', asmMode, operand, undefined, comment);
  }

  /**
   * INX - Increment X.
   */
  public inx(comment?: string): this {
    return this.instruction('INX', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * INY - Increment Y.
   */
  public iny(comment?: string): this {
    return this.instruction('INY', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * DEX - Decrement X.
   */
  public dex(comment?: string): this {
    return this.instruction('DEX', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * DEY - Decrement Y.
   */
  public dey(comment?: string): this {
    return this.instruction('DEY', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  // ==========================================================================
  // Logical/Bitwise Instructions
  // ==========================================================================

  /**
   * AND - Logical AND.
   */
  public and(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('AND', asmMode, operand, undefined, comment);
  }

  /**
   * ORA - Logical OR.
   */
  public ora(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('ORA', asmMode, operand, undefined, comment);
  }

  /**
   * EOR - Exclusive OR.
   */
  public eor(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('EOR', asmMode, operand, undefined, comment);
  }

  /**
   * ASL - Arithmetic Shift Left.
   */
  public asl(
    operand?: number,
    mode: 'accumulator' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' = 'accumulator',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('ASL', asmMode, operand, undefined, comment);
  }

  /**
   * LSR - Logical Shift Right.
   */
  public lsr(
    operand?: number,
    mode: 'accumulator' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' = 'accumulator',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('LSR', asmMode, operand, undefined, comment);
  }

  /**
   * ROL - Rotate Left.
   */
  public rol(
    operand?: number,
    mode: 'accumulator' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' = 'accumulator',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('ROL', asmMode, operand, undefined, comment);
  }

  /**
   * ROR - Rotate Right.
   */
  public ror(
    operand?: number,
    mode: 'accumulator' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' = 'accumulator',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('ROR', asmMode, operand, undefined, comment);
  }

  // ==========================================================================
  // Comparison Instructions
  // ==========================================================================

  /**
   * CMP - Compare Accumulator.
   */
  public cmp(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX' | 'absoluteY' | 'indirectX' | 'indirectY',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('CMP', asmMode, operand, undefined, comment);
  }

  /**
   * CPX - Compare X Register.
   */
  public cpx(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'absolute',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('CPX', asmMode, operand, undefined, comment);
  }

  /**
   * CPY - Compare Y Register.
   */
  public cpy(
    operand: number,
    mode: 'immediate' | 'zeroPage' | 'absolute',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('CPY', asmMode, operand, undefined, comment);
  }

  // ==========================================================================
  // Branch Instructions
  // ==========================================================================

  /**
   * BEQ - Branch if Equal.
   */
  public beq(label: string, comment?: string): this {
    return this.instruction('BEQ', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * BNE - Branch if Not Equal.
   */
  public bne(label: string, comment?: string): this {
    return this.instruction('BNE', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * BCC - Branch if Carry Clear.
   */
  public bcc(label: string, comment?: string): this {
    return this.instruction('BCC', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * BCS - Branch if Carry Set.
   */
  public bcs(label: string, comment?: string): this {
    return this.instruction('BCS', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * BPL - Branch if Plus.
   */
  public bpl(label: string, comment?: string): this {
    return this.instruction('BPL', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * BMI - Branch if Minus.
   */
  public bmi(label: string, comment?: string): this {
    return this.instruction('BMI', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * BVC - Branch if Overflow Clear.
   */
  public bvc(label: string, comment?: string): this {
    return this.instruction('BVC', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * BVS - Branch if Overflow Set.
   */
  public bvs(label: string, comment?: string): this {
    return this.instruction('BVS', AsmAddressingMode.Relative, undefined, label, comment);
  }

  // ==========================================================================
  // Jump/Call Instructions
  // ==========================================================================

  /**
   * JMP - Jump.
   */
  public jmp(target: string | number, isIndirect: boolean = false, comment?: string): this {
    const mode = isIndirect ? AsmAddressingMode.Indirect : AsmAddressingMode.Absolute;
    if (typeof target === 'string') {
      return this.instruction('JMP', mode, undefined, target, comment);
    }
    return this.instruction('JMP', mode, target, undefined, comment);
  }

  /**
   * JSR - Jump to Subroutine.
   */
  public jsr(target: string | number, comment?: string): this {
    if (typeof target === 'string') {
      return this.instruction('JSR', AsmAddressingMode.Absolute, undefined, target, comment);
    }
    return this.instruction('JSR', AsmAddressingMode.Absolute, target, undefined, comment);
  }

  /**
   * RTS - Return from Subroutine.
   */
  public rts(comment?: string): this {
    return this.instruction('RTS', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * RTI - Return from Interrupt.
   */
  public rti(comment?: string): this {
    return this.instruction('RTI', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  // ==========================================================================
  // Flag Instructions
  // ==========================================================================

  /**
   * CLC - Clear Carry.
   */
  public clc(comment?: string): this {
    return this.instruction('CLC', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * SEC - Set Carry.
   */
  public sec(comment?: string): this {
    return this.instruction('SEC', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * CLI - Clear Interrupt.
   */
  public cli(comment?: string): this {
    return this.instruction('CLI', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * SEI - Set Interrupt.
   */
  public sei(comment?: string): this {
    return this.instruction('SEI', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * CLD - Clear Decimal.
   */
  public cld(comment?: string): this {
    return this.instruction('CLD', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * SED - Set Decimal.
   */
  public sed(comment?: string): this {
    return this.instruction('SED', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * CLV - Clear Overflow.
   */
  public clv(comment?: string): this {
    return this.instruction('CLV', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  // ==========================================================================
  // Stack Instructions
  // ==========================================================================

  /**
   * PHA - Push Accumulator.
   */
  public pha(comment?: string): this {
    return this.instruction('PHA', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * PLA - Pull Accumulator.
   */
  public pla(comment?: string): this {
    return this.instruction('PLA', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * PHP - Push Processor Status.
   */
  public php(comment?: string): this {
    return this.instruction('PHP', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * PLP - Pull Processor Status.
   */
  public plp(comment?: string): this {
    return this.instruction('PLP', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  // ==========================================================================
  // Transfer Instructions
  // ==========================================================================

  /**
   * TAX - Transfer A to X.
   */
  public tax(comment?: string): this {
    return this.instruction('TAX', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * TAY - Transfer A to Y.
   */
  public tay(comment?: string): this {
    return this.instruction('TAY', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * TXA - Transfer X to A.
   */
  public txa(comment?: string): this {
    return this.instruction('TXA', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * TYA - Transfer Y to A.
   */
  public tya(comment?: string): this {
    return this.instruction('TYA', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * TSX - Transfer SP to X.
   */
  public tsx(comment?: string): this {
    return this.instruction('TSX', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * TXS - Transfer X to SP.
   */
  public txs(comment?: string): this {
    return this.instruction('TXS', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  // ==========================================================================
  // Misc Instructions
  // ==========================================================================

  /**
   * NOP - No Operation.
   */
  public nop(comment?: string): this {
    return this.instruction('NOP', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * BRK - Break.
   */
  public brk(comment?: string): this {
    return this.instruction('BRK', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * BIT - Bit Test.
   */
  public bit(operand: number, mode: 'zeroPage' | 'absolute', comment?: string): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('BIT', asmMode, operand, undefined, comment);
  }

  // ==========================================================================
  // 65C02-Specific Instructions
  // ==========================================================================
  // These helpers emit instructions exclusive to the WDC 65C02 CPU.
  // They MUST only be used when targeting a 65C02 platform (e.g., X16).
  // On a base MOS 6502, these opcodes do not exist and would crash.

  /**
   * STZ - Store Zero (65C02 only).
   *
   * Stores zero to memory without clobbering the accumulator.
   * On the base 6502, this requires LDA #0 + STA which destroys A.
   *
   * Supported modes: zeroPage, zeroPageX, absolute, absoluteX.
   *
   * @param operand - Memory address to store zero at
   * @param mode - Addressing mode
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public stz(
    operand: number,
    mode: 'zeroPage' | 'zeroPageX' | 'absolute' | 'absoluteX',
    comment?: string
  ): this {
    const asmMode = this.mapMode(mode);
    return this.instruction('STZ', asmMode, operand, undefined, comment);
  }

  /**
   * BRA - Branch Always (65C02 only).
   *
   * Unconditional relative branch (±127 bytes range).
   * Saves 1 byte compared to the 6502's JMP absolute (3 bytes vs 2 bytes).
   *
   * @param label - Target label to branch to
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public bra(label: string, comment?: string): this {
    return this.instruction('BRA', AsmAddressingMode.Relative, undefined, label, comment);
  }

  /**
   * INA - Increment Accumulator (65C02 only).
   *
   * Emits INC with accumulator addressing mode (INC A).
   * Single byte instruction. Does NOT affect the carry flag,
   * unlike the 6502 equivalent (CLC + ADC #1).
   *
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public ina(comment?: string): this {
    return this.instruction('INC', AsmAddressingMode.Accumulator, undefined, undefined, comment);
  }

  /**
   * DEA - Decrement Accumulator (65C02 only).
   *
   * Emits DEC with accumulator addressing mode (DEC A).
   * Single byte instruction. Does NOT affect the carry flag,
   * unlike the 6502 equivalent (SEC + SBC #1).
   *
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public dea(comment?: string): this {
    return this.instruction('DEC', AsmAddressingMode.Accumulator, undefined, undefined, comment);
  }

  /**
   * PHX - Push X Register (65C02 only).
   *
   * Pushes X directly onto the stack without clobbering A.
   * On the base 6502, this requires TXA + PHA which destroys A.
   *
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public phx(comment?: string): this {
    return this.instruction('PHX', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * PLX - Pull X Register (65C02 only).
   *
   * Pulls X directly from the stack without clobbering A.
   * On the base 6502, this requires PLA + TAX which destroys A.
   *
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public plx(comment?: string): this {
    return this.instruction('PLX', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * PHY - Push Y Register (65C02 only).
   *
   * Pushes Y directly onto the stack without clobbering A.
   * On the base 6502, this requires TYA + PHA which destroys A.
   *
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public phy(comment?: string): this {
    return this.instruction('PHY', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  /**
   * PLY - Pull Y Register (65C02 only).
   *
   * Pulls Y directly from the stack without clobbering A.
   * On the base 6502, this requires PLA + TAY which destroys A.
   *
   * @param comment - Optional comment
   * @returns this for chaining
   */
  public ply(comment?: string): this {
    return this.instruction('PLY', AsmAddressingMode.Implied, undefined, undefined, comment);
  }

  // ==========================================================================
  // Build
  // ==========================================================================

  /**
   * Builds and returns the ASM-IL program.
   *
   * @returns Complete ASM-IL program
   */
  public build(): AsmILProgram {
    // Update stats
    this.program.stats = {
      instructionCount: this.instructionCount,
      labelCount: this.labelCount,
      estimatedBytes: this.estimatedBytes,
      estimatedCycles: this.estimatedCycles,
    };
    return this.program;
  }

  /**
   * Gets all elements across all sections.
   */
  public getAllElements(): AsmILElement[] {
    const elements: AsmILElement[] = [];
    for (const section of this.program.sections) {
      elements.push(...section.elements);
    }
    return elements;
  }

  // ==========================================================================
  // Internal Helpers
  // ==========================================================================

  /**
   * Maps simplified mode names to AsmAddressingMode enum.
   */
  protected mapMode(
    mode:
      | 'immediate'
      | 'zeroPage'
      | 'zeroPageX'
      | 'zeroPageY'
      | 'absolute'
      | 'absoluteX'
      | 'absoluteY'
      | 'indirect'
      | 'indirectX'
      | 'indirectY'
      | 'accumulator'
  ): AsmAddressingMode {
    switch (mode) {
      case 'immediate':
        return AsmAddressingMode.Immediate;
      case 'zeroPage':
        return AsmAddressingMode.ZeroPage;
      case 'zeroPageX':
        return AsmAddressingMode.ZeroPageX;
      case 'zeroPageY':
        return AsmAddressingMode.ZeroPageY;
      case 'absolute':
        return AsmAddressingMode.Absolute;
      case 'absoluteX':
        return AsmAddressingMode.AbsoluteX;
      case 'absoluteY':
        return AsmAddressingMode.AbsoluteY;
      case 'indirect':
        return AsmAddressingMode.Indirect;
      case 'indirectX':
        return AsmAddressingMode.IndexedIndirect;
      case 'indirectY':
        return AsmAddressingMode.IndirectIndexed;
      case 'accumulator':
        return AsmAddressingMode.Accumulator;
    }
  }

  /**
   * Adds estimated cost for an instruction.
   */
  protected addCostEstimate(mnemonic: string, mode: AsmAddressingMode): void {
    // Basic cost estimates
    let bytes = 1;
    let cycles = 2;

    switch (mode) {
      case AsmAddressingMode.Implied:
      case AsmAddressingMode.Accumulator:
        bytes = 1;
        cycles = 2;
        break;
      case AsmAddressingMode.Immediate:
      case AsmAddressingMode.ZeroPage:
      case AsmAddressingMode.ZeroPageX:
      case AsmAddressingMode.ZeroPageY:
      case AsmAddressingMode.Relative:
        bytes = 2;
        cycles = 3;
        break;
      case AsmAddressingMode.Absolute:
      case AsmAddressingMode.AbsoluteX:
      case AsmAddressingMode.AbsoluteY:
      case AsmAddressingMode.Indirect:
        bytes = 3;
        cycles = 4;
        break;
      case AsmAddressingMode.IndexedIndirect:
      case AsmAddressingMode.IndirectIndexed:
        bytes = 2;
        cycles = 6;
        break;
    }

    // Adjust for specific instructions
    if (mnemonic === 'JSR') {
      cycles = 6;
    } else if (mnemonic === 'RTS') {
      cycles = 6;
    } else if (mnemonic === 'JMP' && mode === AsmAddressingMode.Indirect) {
      cycles = 5;
    }

    this.estimatedBytes += bytes;
    this.estimatedCycles += cycles;
  }
}