/**
 * ASM-IL Emitter
 *
 * Converts an AsmILProgram (structured 6502 assembly representation)
 * into ACME assembler text output. This is the final stage of the
 * compilation pipeline:
 *
 *   Source → Lexer → Parser → Semantic → IL → CodeGen → **Emitter** → .asm
 *
 * The emitter walks every section and element in the program, formatting
 * each instruction, label, directive, comment, blank line, and data block
 * according to ACME assembler syntax conventions.
 *
 * @module codegen/asm-il/emitter
 */

import type {
  AsmILProgram,
  AsmILSection,
  AsmILElement,
  AsmInstruction,
  AsmLabel,
  AsmDirective,
  AsmComment,
  AsmData,
} from './types.js';

import { AsmAddressingMode } from './types.js';

// ============================================================================
// Emitter Options
// ============================================================================

/**
 * Configuration options for the ASM-IL emitter.
 *
 * Controls formatting preferences such as indentation, hex casing,
 * and whether to include section separators in the output.
 */
export interface AsmILEmitterOptions {
  /** Number of spaces for instruction indentation (default: 2) */
  indentSize: number;

  /** Use uppercase hex digits, e.g. $FF vs $ff (default: true) */
  upperCaseHex: boolean;

  /** Include section separator comments in output (default: true) */
  includeSectionSeparators: boolean;

  /** Include a file header comment with module name (default: true) */
  includeHeader: boolean;

  /** Include stats as a trailing comment block (default: false) */
  includeStats: boolean;
}

/**
 * Default emitter options.
 *
 * Produces clean, readable ACME output with 2-space indentation,
 * uppercase hex, and section separators enabled.
 */
export const DEFAULT_EMITTER_OPTIONS: AsmILEmitterOptions = {
  indentSize: 2,
  upperCaseHex: true,
  includeSectionSeparators: true,
  includeHeader: true,
  includeStats: false,
};

// ============================================================================
// Emitter Class
// ============================================================================

/**
 * Emits ACME assembler text from an AsmILProgram.
 *
 * Walks the program's sections and elements, formatting each one
 * into a line (or lines) of ACME-compatible assembly text.
 *
 * @example
 * ```typescript
 * const emitter = new AsmILEmitter();
 * const asmText = emitter.emit(program);
 * // asmText is a string ready to be written to a .asm file
 * ```
 */
export class AsmILEmitter {
  /** Merged options (defaults + user overrides) */
  protected options: AsmILEmitterOptions;

  /** Indentation string, built from options.indentSize */
  protected indent: string;

  /**
   * Creates a new ASM-IL emitter.
   *
   * @param options - Partial options to override defaults
   */
  constructor(options: Partial<AsmILEmitterOptions> = {}) {
    this.options = { ...DEFAULT_EMITTER_OPTIONS, ...options };
    this.indent = ' '.repeat(this.options.indentSize);
  }

  // ==========================================================================
  // Public API
  // ==========================================================================

  /**
   * Emits the entire AsmILProgram as ACME assembler text.
   *
   * Walks all sections in order, emitting each element within.
   * Optionally includes a file header and trailing stats block.
   *
   * @param program - The AsmILProgram to emit
   * @returns Complete ACME assembler text (newline-terminated)
   */
  public emit(program: AsmILProgram): string {
    const lines: string[] = [];

    // Optional file header
    if (this.options.includeHeader) {
      lines.push(`; Generated by Blend65 compiler`);
      lines.push(`; Module: ${program.moduleName}`);
      lines.push('');
    }

    // Emit each section
    for (let i = 0; i < program.sections.length; i++) {
      const section = program.sections[i];

      // Optional section separator comment
      if (this.options.includeSectionSeparators) {
        // Add a blank line before non-first sections for readability
        if (i > 0) {
          lines.push('');
        }
        lines.push(`; --- Section: ${section.name} ---`);
      }

      this.emitSection(section, lines);
    }

    // Optional stats footer
    if (this.options.includeStats) {
      lines.push('');
      lines.push('; --- Statistics ---');
      lines.push(`; Instructions: ${program.stats.instructionCount}`);
      lines.push(`; Labels: ${program.stats.labelCount}`);
      lines.push(`; Estimated bytes: ${program.stats.estimatedBytes}`);
      lines.push(`; Estimated cycles: ${program.stats.estimatedCycles}`);
    }

    // Ensure trailing newline
    return lines.join('\n') + '\n';
  }

  // ==========================================================================
  // Section Emission
  // ==========================================================================

  /**
   * Emits all elements within a single section.
   *
   * @param section - The section to emit
   * @param lines - Accumulator array for output lines
   */
  protected emitSection(section: AsmILSection, lines: string[]): void {
    for (const element of section.elements) {
      const line = this.emitElement(element);
      lines.push(line);
    }
  }

  // ==========================================================================
  // Element Dispatch
  // ==========================================================================

  /**
   * Emits a single AsmILElement to a line of text.
   *
   * Dispatches on element.kind to the appropriate sub-emitter.
   *
   * @param element - The element to emit
   * @returns A single line of ACME assembler text
   */
  protected emitElement(element: AsmILElement): string {
    switch (element.kind) {
      case 'instruction':
        return this.emitInstruction(element.instruction);
      case 'label':
        return this.emitLabel(element.label);
      case 'directive':
        return this.emitDirective(element.directive);
      case 'comment':
        return this.emitComment(element.comment);
      case 'blank':
        return '';
      case 'data':
        return this.emitData(element.data);
    }
  }

  // ==========================================================================
  // Instruction Emission
  // ==========================================================================

  /**
   * Emits a 6502 instruction in ACME syntax.
   *
   * Formats the mnemonic, addressing-mode-specific operand, and optional
   * inline comment into a single indented line.
   *
   * @param instr - The instruction to emit
   * @returns Formatted instruction line (e.g., "  LDA #$FF ; load max")
   */
  protected emitInstruction(instr: AsmInstruction): string {
    const operand = this.formatOperand(instr);
    const base = operand
      ? `${this.indent}${instr.mnemonic} ${operand}`
      : `${this.indent}${instr.mnemonic}`;

    if (instr.comment) {
      return `${base} ; ${instr.comment}`;
    }
    return base;
  }

  /**
   * Formats the operand portion of an instruction based on its addressing mode.
   *
   * Each addressing mode has a distinct syntax in ACME:
   * - Implied/Accumulator: no operand (or "A" pseudo-operand is omitted)
   * - Immediate: #$XX
   * - ZeroPage: $XX
   * - Absolute: $XXXX
   * - Indexed: $XXXX,X / $XXXX,Y
   * - Indirect: ($XXXX) / ($XX,X) / ($XX),Y
   * - Relative: label (for branches)
   *
   * @param instr - The instruction whose operand to format
   * @returns Formatted operand string, or empty string for implied mode
   */
  protected formatOperand(instr: AsmInstruction): string {
    const { mode, operand, labelOperand } = instr;

    switch (mode) {
      case AsmAddressingMode.Implied:
        return '';

      case AsmAddressingMode.Accumulator:
        // ACME uses bare mnemonic for accumulator mode (e.g., ASL not ASL A)
        return '';

      case AsmAddressingMode.Immediate:
        // Support label operands for address-of expressions (e.g., LDA #<label / LDX #>label).
        // The @ operator generates LOAD_ADDRESS which produces immediate label references
        // that ACME resolves at assembly time to the actual address bytes.
        if (labelOperand) {
          return `#${labelOperand}`;
        }
        return `#${this.formatHex(operand ?? 0)}`;

      case AsmAddressingMode.ZeroPage:
        return this.formatHex(operand ?? 0);

      case AsmAddressingMode.ZeroPageX:
        return `${this.formatHex(operand ?? 0)},X`;

      case AsmAddressingMode.ZeroPageY:
        return `${this.formatHex(operand ?? 0)},Y`;

      case AsmAddressingMode.Absolute:
        // Label operands are used for JMP/JSR to named targets
        if (labelOperand) {
          return labelOperand;
        }
        return this.formatHex(operand ?? 0);

      case AsmAddressingMode.AbsoluteX:
        // Support label operands for indexed addressing (e.g., LDA __data_label,X)
        if (labelOperand) {
          return `${labelOperand},X`;
        }
        return `${this.formatHex(operand ?? 0)},X`;

      case AsmAddressingMode.AbsoluteY:
        // Support label operands for indexed addressing (e.g., LDA __data_label,Y)
        // This is critical for @data const array access where the base address
        // is an ACME label resolved at assembly time.
        if (labelOperand) {
          return `${labelOperand},Y`;
        }
        return `${this.formatHex(operand ?? 0)},Y`;

      case AsmAddressingMode.Indirect:
        if (labelOperand) {
          return `(${labelOperand})`;
        }
        return `(${this.formatHex(operand ?? 0)})`;

      case AsmAddressingMode.IndexedIndirect:
        return `(${this.formatHex(operand ?? 0)},X)`;

      case AsmAddressingMode.IndirectIndexed:
        return `(${this.formatHex(operand ?? 0)}),Y`;

      case AsmAddressingMode.Relative:
        // Branches always use label operands
        if (labelOperand) {
          return labelOperand;
        }
        // Fallback: emit numeric offset (unusual but possible)
        return this.formatHex(operand ?? 0);
    }
  }

  // ==========================================================================
  // Label Emission
  // ==========================================================================

  /**
   * Emits a label definition in ACME syntax.
   *
   * Global labels are emitted as `name:` at column 0.
   * Local labels (prefixed with `.`) are also at column 0.
   *
   * @param label - The label to emit
   * @returns Formatted label line (e.g., "main:" or ".loop:")
   */
  protected emitLabel(label: AsmLabel): string {
    // Local labels in ACME start with a dot and have no colon
    // Global labels end with a colon
    const name = label.isLocal && !label.name.startsWith('.')
      ? `.${label.name}`
      : label.name;

    const base = label.isLocal ? name : `${name}:`;

    if (label.comment) {
      return `${base} ; ${label.comment}`;
    }
    return base;
  }

  // ==========================================================================
  // Directive Emission
  // ==========================================================================

  /**
   * Emits an assembler directive in ACME syntax.
   *
   * Handles origin directives (*=), byte/word data directives (!byte, !word),
   * and other ACME pseudo-ops.
   *
   * @param directive - The directive to emit
   * @returns Formatted directive line (e.g., "*= $0801" or "!byte $0C, $08")
   */
  protected emitDirective(directive: AsmDirective): string {
    let line: string;

    if (directive.values && directive.values.length > 0) {
      // Multi-value directive (e.g., !byte $0C, $08, $0A)
      const hexValues = directive.values.map(v => this.formatHex(v)).join(', ');
      line = `${this.indent}${directive.directive} ${hexValues}`;
    } else if (directive.value !== undefined) {
      // Single-value directive
      const val = typeof directive.value === 'number'
        ? this.formatHex(directive.value)
        : directive.value;
      line = `${this.indent}${directive.directive} ${val}`;
    } else {
      // Bare directive (no value)
      line = `${this.indent}${directive.directive}`;
    }

    if (directive.comment) {
      return `${line} ; ${directive.comment}`;
    }
    return line;
  }

  // ==========================================================================
  // Comment Emission
  // ==========================================================================

  /**
   * Emits a full-line comment.
   *
   * @param comment - The comment to emit
   * @returns Formatted comment line (e.g., "; This is a comment")
   */
  protected emitComment(comment: AsmComment): string {
    return `; ${comment.text}`;
  }

  // ==========================================================================
  // Data Emission
  // ==========================================================================

  /**
   * Emits raw data bytes as an ACME !byte directive.
   *
   * @param data - The data element to emit
   * @returns Formatted data line (e.g., "  !byte $0C, $08, $0A, $00")
   */
  protected emitData(data: AsmData): string {
    const hexBytes = data.bytes.map(b => this.formatHex(b)).join(', ');
    const line = `${this.indent}!byte ${hexBytes}`;

    if (data.comment) {
      return `${line} ; ${data.comment}`;
    }
    return line;
  }

  // ==========================================================================
  // Hex Formatting
  // ==========================================================================

  /**
   * Formats a number as a hex string with $ prefix.
   *
   * Automatically chooses byte ($XX) or word ($XXXX) width based on value.
   * Zero-page values (0-255) use 2-digit hex, larger values use 4-digit hex.
   *
   * @param value - The number to format
   * @returns Hex string (e.g., "$FF" or "$D020")
   */
  protected formatHex(value: number): string {
    // Determine width: 2 digits for byte-range, 4 digits for word-range
    const width = value <= 0xFF ? 2 : 4;
    const hex = (value & 0xFFFF).toString(16).padStart(width, '0');

    return this.options.upperCaseHex
      ? `$${hex.toUpperCase()}`
      : `$${hex}`;
  }
}
