/**
 * AST to IL Transformer for Blend65
 * Task 2.3: Create AST to IL Transformer
 *
 * This file implements the transformation from validated Blend65 AST to IL representation.
 * The transformer uses the visitor pattern to systematically convert each AST node type
 * to appropriate IL instruction sequences.
 *
 * Key Responsibilities:
 * - Transform all Blend65 language constructs to IL instructions
 * - Generate temporary variables for complex expression evaluation
 * - Integrate semantic analysis optimization metadata into IL
 * - Handle all storage classes and addressing mode preferences
 * - Support callback function transformation and indirect calls
 * - Generate proper control flow graphs for optimization passes
 *
 * Educational Focus:
 * - How compilers transform high-level constructs to intermediate representation
 * - Temporary variable management in expression evaluation
 * - Control flow transformation for optimization-friendly representation
 * - Integration of semantic analysis metadata with code generation
 */
import type { Program } from '@blend65/ast';
import type { Symbol } from '@blend65/semantic';
import { ILProgram, ILModule, ILFunction, ILInstruction, ILValue, ILTemporary } from './il-types';
/**
 * Result of AST to IL transformation.
 */
export interface TransformationResult {
    success: boolean;
    program: ILProgram;
    errors: TransformationError[];
    warnings: TransformationWarning[];
}
/**
 * Transformation error information.
 */
export interface TransformationError {
    message: string;
    location?: any;
    astNode?: any;
}
/**
 * Transformation warning information.
 */
export interface TransformationWarning {
    message: string;
    location?: any;
    astNode?: any;
}
/**
 * Result of expression transformation.
 * Contains the IL value representing the expression result and any generated instructions.
 */
export interface ExpressionTransformResult {
    /** IL value representing the expression result */
    value: ILValue;
    /** Instructions generated to evaluate the expression */
    instructions: ILInstruction[];
    /** Temporary variables generated (for cleanup) */
    temporaries: ILTemporary[];
}
/**
 * Result of statement transformation.
 */
export interface StatementTransformResult {
    /** Instructions generated for the statement */
    instructions: ILInstruction[];
    /** Whether the statement always transfers control (return, break, etc.) */
    alwaysTransfersControl: boolean;
    /** Labels generated by the statement */
    labels: Map<string, number>;
}
/**
 * Context maintained during AST to IL transformation.
 * Tracks state needed for generating correct IL instructions.
 */
export interface TransformationContext {
    /** Current module being transformed */
    currentModule: ILModule;
    /** Current function being transformed */
    currentFunction: ILFunction | null;
    /** Symbol table from semantic analysis */
    symbolTable: Map<string, Symbol>;
    /** Next unique temporary variable ID */
    nextTemporaryId: number;
    /** Next unique instruction ID */
    nextInstructionId: number;
    /** Current break target label (for break statements) */
    breakTarget: string | null;
    /** Current continue target label (for continue statements) */
    continueTarget: string | null;
    /** Label generation counter */
    labelCounter: number;
    /** Error collector */
    errors: TransformationError[];
    /** Warnings collector */
    warnings: TransformationWarning[];
    /** Optimization metadata integration flag */
    useOptimizationMetadata: boolean;
    /** Target platform for optimization hints */
    targetPlatform: string;
}
/**
 * Main AST to IL transformer class.
 * Implements the visitor pattern to transform AST nodes to IL instructions.
 */
export declare class ASTToILTransformer {
    private context;
    constructor(symbolTable: Map<string, Symbol>, options?: {
        useOptimizationMetadata?: boolean;
        targetPlatform?: string;
    });
    /**
     * Transform a complete Blend65 program to IL.
     */
    transformProgram(program: Program): TransformationResult;
    private transformImport;
    private transformExport;
    private transformDeclaration;
    private transformFunctionDeclaration;
    private transformVariableDeclaration;
    private transformLocalVariableDeclaration;
    private transformModuleVariableDeclaration;
    private transformTypeDeclaration;
    private transformEnumDeclaration;
    private transformStatement;
    private transformExpressionStatement;
    private transformReturnStatement;
    private transformIfStatement;
    private transformMatchStatement;
    private transformBlockStatement;
    private transformBreakStatement;
    private transformContinueStatement;
    private transformExpression;
    private transformBinaryExpression;
    private transformUnaryExpression;
    private transformAssignmentExpression;
    private transformCallExpression;
    private transformMemberExpression;
    private transformIndexExpression;
    private transformIdentifier;
    private transformLiteral;
    private transformArrayLiteral;
    private addError;
    private getSymbol;
    private determineImportType;
    private generateLabel;
    private transformType;
    private isVoidType;
    private createDefaultValue;
    private determineParameterPassingMethod;
    private createParameterOptimizationHints;
    private determineLocalVariableAllocation;
    private createLocalVariableOptimizationHints;
    private createVariableOptimizationHints;
    private evaluateConstantExpression;
    private inferBinaryExpressionType;
    private inferUnaryExpressionType;
    private inferLiteralType;
    private getConstantRepresentation;
    private transformWhileStatement;
    private transformForStatement;
}
/**
 * Create a new AST to IL transformer instance.
 */
export declare function createASTToILTransformer(symbolTable: Map<string, Symbol>, options?: {
    useOptimizationMetadata?: boolean;
    targetPlatform?: string;
}): ASTToILTransformer;
/**
 * Transform a complete Blend65 program to IL.
 * Convenience function for one-shot transformation.
 */
export declare function transformProgramToIL(program: Program, symbolTable: Map<string, Symbol>, options?: {
    useOptimizationMetadata?: boolean;
    targetPlatform?: string;
}): TransformationResult;
//# sourceMappingURL=ast-to-il.d.ts.map