/**
 * ASM-IL Emitter Unit Tests
 *
 * Verifies that AsmILEmitter correctly converts AsmILProgram structures
 * into ACME assembler text output for all element kinds and addressing modes.
 *
 * @module __tests__/codegen/asm-il/emitter
 */

import { describe, it, expect } from 'vitest';
import {
  AsmILEmitter,
  AsmILEmitterOptions,
  DEFAULT_EMITTER_OPTIONS,
} from '../../../../codegen/asm-il/emitter.js';
import { AsmILBuilder } from '../../../../codegen/asm-il/builder.js';
import {
  AsmAddressingMode,
  AsmILProgram,
  createAsmILProgram,
  createSection,
  createInstructionElement,
  createLabelElement,
  createDirectiveElement,
  createCommentElement,
  createBlankElement,
  createDataElement,
} from '../../../../codegen/asm-il/types.js';

// ============================================================================
// Helpers
// ============================================================================

/**
 * Creates an emitter with all optional output disabled for minimal output.
 * This makes it easier to assert exact output without header/separator noise.
 */
function minimalEmitter(overrides: Partial<AsmILEmitterOptions> = {}): AsmILEmitter {
  return new AsmILEmitter({
    includeHeader: false,
    includeSectionSeparators: false,
    includeStats: false,
    ...overrides,
  });
}

/**
 * Builds a program with a single section containing given elements.
 */
function programWith(
  ...elements: ReturnType<typeof createInstructionElement>[]
): AsmILProgram {
  const program = createAsmILProgram('test');
  const section = createSection('code');
  section.elements.push(...elements);
  program.sections.push(section);
  return program;
}

// ============================================================================
// Constructor & Default Options
// ============================================================================

describe('AsmILEmitter', () => {
  describe('constructor and options', () => {
    it('should use default options when none provided', () => {
      const emitter = new AsmILEmitter();
      // Verify defaults are applied by emitting a minimal program
      const program = createAsmILProgram('test');
      const output = emitter.emit(program);
      // Default includes header
      expect(output).toContain('; Generated by Blend65 compiler');
      expect(output).toContain('; Module: test');
    });

    it('should merge user options with defaults', () => {
      const emitter = new AsmILEmitter({ includeHeader: false });
      const program = createAsmILProgram('test');
      const output = emitter.emit(program);
      // Header disabled
      expect(output).not.toContain('; Generated by Blend65 compiler');
    });

    it('should respect custom indent size', () => {
      const emitter = minimalEmitter({ indentSize: 4 });
      const program = programWith(
        createInstructionElement('NOP', AsmAddressingMode.Implied)
      );
      const output = emitter.emit(program);
      expect(output).toContain('    NOP');
    });

    it('should export DEFAULT_EMITTER_OPTIONS with expected values', () => {
      expect(DEFAULT_EMITTER_OPTIONS.indentSize).toBe(2);
      expect(DEFAULT_EMITTER_OPTIONS.upperCaseHex).toBe(true);
      expect(DEFAULT_EMITTER_OPTIONS.includeSectionSeparators).toBe(true);
      expect(DEFAULT_EMITTER_OPTIONS.includeHeader).toBe(true);
      expect(DEFAULT_EMITTER_OPTIONS.includeStats).toBe(false);
    });
  });

  // ==========================================================================
  // Header and Footer
  // ==========================================================================

  describe('header and footer', () => {
    it('should include module name in header', () => {
      const emitter = new AsmILEmitter();
      const program = createAsmILProgram('my-module');
      const output = emitter.emit(program);
      expect(output).toContain('; Module: my-module');
    });

    it('should include stats footer when enabled', () => {
      const emitter = new AsmILEmitter({ includeStats: true });
      const program = createAsmILProgram('test');
      program.stats = {
        instructionCount: 10,
        labelCount: 3,
        estimatedBytes: 25,
        estimatedCycles: 40,
      };
      const output = emitter.emit(program);
      expect(output).toContain('; --- Statistics ---');
      expect(output).toContain('; Instructions: 10');
      expect(output).toContain('; Labels: 3');
      expect(output).toContain('; Estimated bytes: 25');
      expect(output).toContain('; Estimated cycles: 40');
    });

    it('should not include stats by default', () => {
      const emitter = new AsmILEmitter();
      const program = createAsmILProgram('test');
      const output = emitter.emit(program);
      expect(output).not.toContain('; --- Statistics ---');
    });
  });

  // ==========================================================================
  // Section Separators
  // ==========================================================================

  describe('section separators', () => {
    it('should include section separator comments when enabled', () => {
      const emitter = new AsmILEmitter({
        includeHeader: false,
        includeSectionSeparators: true,
      });
      const program = createAsmILProgram('test');
      program.sections.push(createSection('code'));
      const output = emitter.emit(program);
      expect(output).toContain('; --- Section: code ---');
    });

    it('should omit section separators when disabled', () => {
      const emitter = minimalEmitter();
      const program = createAsmILProgram('test');
      program.sections.push(createSection('code'));
      const output = emitter.emit(program);
      expect(output).not.toContain('; --- Section:');
    });

    it('should add blank line between sections', () => {
      const emitter = new AsmILEmitter({
        includeHeader: false,
        includeSectionSeparators: true,
      });
      const program = createAsmILProgram('test');
      program.sections.push(createSection('header'));
      program.sections.push(createSection('code'));
      const output = emitter.emit(program);
      const lines = output.split('\n');
      // Find the second section separator and check a blank line precedes it
      const codeIdx = lines.findIndex(l => l.includes('Section: code'));
      expect(codeIdx).toBeGreaterThan(0);
      expect(lines[codeIdx - 1]).toBe('');
    });
  });

  // ==========================================================================
  // Instruction Emission - All Addressing Modes
  // ==========================================================================

  describe('instruction emission', () => {
    const emitter = minimalEmitter();

    it('should emit implied mode (no operand)', () => {
      const program = programWith(
        createInstructionElement('RTS', AsmAddressingMode.Implied)
      );
      expect(emitter.emit(program)).toContain('  RTS');
    });

    it('should emit accumulator mode (no operand)', () => {
      const program = programWith(
        createInstructionElement('ASL', AsmAddressingMode.Accumulator)
      );
      // ACME omits the "A" for accumulator mode
      const output = emitter.emit(program);
      expect(output).toContain('  ASL');
      expect(output).not.toContain('ASL A');
    });

    it('should emit immediate mode (#$XX)', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Immediate, 0xFF)
      );
      expect(emitter.emit(program)).toContain('  LDA #$FF');
    });

    it('should emit immediate mode with zero', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Immediate, 0x00)
      );
      expect(emitter.emit(program)).toContain('  LDA #$00');
    });

    it('should emit zero page mode ($XX)', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.ZeroPage, 0x10)
      );
      expect(emitter.emit(program)).toContain('  LDA $10');
    });

    it('should emit zero page,X mode ($XX,X)', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.ZeroPageX, 0x20)
      );
      expect(emitter.emit(program)).toContain('  LDA $20,X');
    });

    it('should emit zero page,Y mode ($XX,Y)', () => {
      const program = programWith(
        createInstructionElement('LDX', AsmAddressingMode.ZeroPageY, 0x30)
      );
      expect(emitter.emit(program)).toContain('  LDX $30,Y');
    });

    it('should emit absolute mode ($XXXX)', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Absolute, 0xD020)
      );
      expect(emitter.emit(program)).toContain('  LDA $D020');
    });

    it('should emit absolute mode with label operand', () => {
      const program = programWith(
        createInstructionElement('JMP', AsmAddressingMode.Absolute, undefined, 'main')
      );
      expect(emitter.emit(program)).toContain('  JMP main');
    });

    it('should emit absolute,X mode ($XXXX,X)', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.AbsoluteX, 0x1000)
      );
      expect(emitter.emit(program)).toContain('  LDA $1000,X');
    });

    it('should emit absolute,Y mode ($XXXX,Y)', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.AbsoluteY, 0x2000)
      );
      expect(emitter.emit(program)).toContain('  LDA $2000,Y');
    });

    it('should emit indirect mode (($XXXX))', () => {
      const program = programWith(
        createInstructionElement('JMP', AsmAddressingMode.Indirect, 0x3000)
      );
      expect(emitter.emit(program)).toContain('  JMP ($3000)');
    });

    it('should emit indirect mode with label operand', () => {
      const program = programWith(
        createInstructionElement('JMP', AsmAddressingMode.Indirect, undefined, 'vector')
      );
      expect(emitter.emit(program)).toContain('  JMP (vector)');
    });

    it('should emit indexed indirect mode (($XX,X))', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.IndexedIndirect, 0x40)
      );
      expect(emitter.emit(program)).toContain('  LDA ($40,X)');
    });

    it('should emit indirect indexed mode (($XX),Y)', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.IndirectIndexed, 0x50)
      );
      expect(emitter.emit(program)).toContain('  LDA ($50),Y');
    });

    it('should emit relative mode with label', () => {
      const program = programWith(
        createInstructionElement('BEQ', AsmAddressingMode.Relative, undefined, '.loop')
      );
      expect(emitter.emit(program)).toContain('  BEQ .loop');
    });

    it('should emit relative mode with numeric fallback', () => {
      const program = programWith(
        createInstructionElement('BNE', AsmAddressingMode.Relative, 0x10)
      );
      expect(emitter.emit(program)).toContain('  BNE $10');
    });

    it('should append inline comment to instruction', () => {
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Immediate, 0xFF, undefined, 'load max')
      );
      expect(emitter.emit(program)).toContain('  LDA #$FF ; load max');
    });
  });

  // ==========================================================================
  // Label Emission
  // ==========================================================================

  describe('label emission', () => {
    const emitter = minimalEmitter();

    it('should emit global label with colon', () => {
      const program = programWith(createLabelElement('main', false));
      expect(emitter.emit(program)).toContain('main:');
    });

    it('should emit local label with dot prefix (no colon)', () => {
      const program = programWith(createLabelElement('loop', true));
      expect(emitter.emit(program)).toContain('.loop');
      // Local labels in ACME don't have a colon
      expect(emitter.emit(program)).not.toContain('.loop:');
    });

    it('should not double-prefix local label that already has dot', () => {
      const program = programWith(createLabelElement('.done', true));
      const output = emitter.emit(program);
      expect(output).toContain('.done');
      expect(output).not.toContain('..done');
    });

    it('should append comment to label', () => {
      const program = programWith(
        createLabelElement('main', false, 'entry point')
      );
      expect(emitter.emit(program)).toContain('main: ; entry point');
    });

    it('should append comment to local label', () => {
      const program = programWith(
        createLabelElement('skip', true, 'branch target')
      );
      expect(emitter.emit(program)).toContain('.skip ; branch target');
    });
  });

  // ==========================================================================
  // Directive Emission
  // ==========================================================================

  describe('directive emission', () => {
    const emitter = minimalEmitter();

    it('should emit single-value numeric directive', () => {
      const program = programWith(
        createDirectiveElement('*=', 0x0801)
      );
      expect(emitter.emit(program)).toContain('  *= $0801');
    });

    it('should emit single-value string directive', () => {
      const program = programWith(
        createDirectiveElement('!source', 'runtime.asm')
      );
      expect(emitter.emit(program)).toContain('  !source runtime.asm');
    });

    it('should emit multi-value directive', () => {
      const program = programWith(
        createDirectiveElement('!byte', undefined, [0x0C, 0x08, 0x0A])
      );
      expect(emitter.emit(program)).toContain('  !byte $0C, $08, $0A');
    });

    it('should emit bare directive with no value', () => {
      const program = programWith(
        createDirectiveElement('!align')
      );
      expect(emitter.emit(program)).toContain('  !align');
    });

    it('should append comment to directive', () => {
      const program = programWith(
        createDirectiveElement('*=', 0x0801, undefined, 'BASIC start')
      );
      expect(emitter.emit(program)).toContain('  *= $0801 ; BASIC start');
    });
  });

  // ==========================================================================
  // Comment Emission
  // ==========================================================================

  describe('comment emission', () => {
    const emitter = minimalEmitter();

    it('should emit full-line comment with semicolon prefix', () => {
      const program = programWith(createCommentElement('Hello World'));
      expect(emitter.emit(program)).toContain('; Hello World');
    });

    it('should handle empty comment text', () => {
      const program = programWith(createCommentElement(''));
      expect(emitter.emit(program)).toContain('; ');
    });
  });

  // ==========================================================================
  // Blank Line Emission
  // ==========================================================================

  describe('blank line emission', () => {
    const emitter = minimalEmitter();

    it('should emit blank line as empty string', () => {
      const program = programWith(
        createInstructionElement('NOP', AsmAddressingMode.Implied),
        createBlankElement(),
        createInstructionElement('RTS', AsmAddressingMode.Implied)
      );
      const lines = emitter.emit(program).split('\n');
      // Find the blank line between NOP and RTS
      const nopIdx = lines.findIndex(l => l.includes('NOP'));
      const rtsIdx = lines.findIndex(l => l.includes('RTS'));
      expect(rtsIdx - nopIdx).toBe(2); // NOP, blank, RTS
      expect(lines[nopIdx + 1]).toBe('');
    });
  });

  // ==========================================================================
  // Data Emission
  // ==========================================================================

  describe('data emission', () => {
    const emitter = minimalEmitter();

    it('should emit data as !byte directive', () => {
      const program = programWith(
        createDataElement([0x0C, 0x08, 0x0A, 0x00])
      );
      expect(emitter.emit(program)).toContain('  !byte $0C, $08, $0A, $00');
    });

    it('should emit data with comment', () => {
      const program = programWith(
        createDataElement([0xFF], 'fill byte')
      );
      expect(emitter.emit(program)).toContain('  !byte $FF ; fill byte');
    });

    it('should emit single byte data', () => {
      const program = programWith(createDataElement([0x42]));
      expect(emitter.emit(program)).toContain('  !byte $42');
    });
  });

  // ==========================================================================
  // Hex Formatting
  // ==========================================================================

  describe('hex formatting', () => {
    it('should use uppercase hex by default', () => {
      const emitter = minimalEmitter();
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Immediate, 0xAB)
      );
      expect(emitter.emit(program)).toContain('#$AB');
    });

    it('should use lowercase hex when configured', () => {
      const emitter = minimalEmitter({ upperCaseHex: false });
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Immediate, 0xAB)
      );
      expect(emitter.emit(program)).toContain('#$ab');
    });

    it('should format byte values as 2-digit hex', () => {
      const emitter = minimalEmitter();
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.ZeroPage, 0x05)
      );
      expect(emitter.emit(program)).toContain('$05');
    });

    it('should format word values as 4-digit hex', () => {
      const emitter = minimalEmitter();
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Absolute, 0x0400)
      );
      expect(emitter.emit(program)).toContain('$0400');
    });

    it('should handle zero value correctly', () => {
      const emitter = minimalEmitter();
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Immediate, 0)
      );
      expect(emitter.emit(program)).toContain('#$00');
    });

    it('should handle max byte value ($FF)', () => {
      const emitter = minimalEmitter();
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Immediate, 0xFF)
      );
      expect(emitter.emit(program)).toContain('#$FF');
    });

    it('should handle value at byte/word boundary ($100)', () => {
      const emitter = minimalEmitter();
      const program = programWith(
        createInstructionElement('LDA', AsmAddressingMode.Absolute, 0x100)
      );
      expect(emitter.emit(program)).toContain('$0100');
    });
  });

  // ==========================================================================
  // Integration: Builder → Emitter
  // ==========================================================================

  describe('builder to emitter integration', () => {
    it('should emit a complete program built with AsmILBuilder', () => {
      const builder = new AsmILBuilder('hello');
      builder
        .section('header')
        .comment('Hello World for C64')
        .directive('*=', 0x0801)
        .section('code')
        .label('main')
        .lda(0x00, 'immediate', 'border color: black')
        .sta(0xD020, 'absolute')
        .rts();

      const program = builder.build();
      const emitter = new AsmILEmitter({
        includeHeader: true,
        includeSectionSeparators: true,
      });
      const output = emitter.emit(program);

      // Verify structure
      expect(output).toContain('; Module: hello');
      expect(output).toContain('; --- Section: header ---');
      expect(output).toContain('; Hello World for C64');
      expect(output).toContain('  *= $0801');
      expect(output).toContain('; --- Section: code ---');
      expect(output).toContain('main:');
      expect(output).toContain('  LDA #$00 ; border color: black');
      expect(output).toContain('  STA $D020');
      expect(output).toContain('  RTS');
    });

    it('should emit branching code correctly', () => {
      const builder = new AsmILBuilder('loop');
      builder
        .section('code')
        .label('start')
        .ldx(0x00, 'immediate')
        .label('loop', true)
        .inx()
        .cpx(0x10, 'immediate')
        .bne('.loop');

      const emitter = minimalEmitter();
      const output = emitter.emit(builder.build());

      expect(output).toContain('start:');
      expect(output).toContain('.loop');
      expect(output).toContain('  LDX #$00');
      expect(output).toContain('  INX');
      expect(output).toContain('  CPX #$10');
      expect(output).toContain('  BNE .loop');
    });

    it('should emit 65C02 instructions', () => {
      const builder = new AsmILBuilder('c02test');
      builder
        .section('code')
        .stz(0xD020, 'absolute')
        .bra('.next')
        .label('next', true)
        .ina()
        .dea()
        .phx()
        .plx()
        .phy()
        .ply();

      const emitter = minimalEmitter();
      const output = emitter.emit(builder.build());

      expect(output).toContain('  STZ $D020');
      expect(output).toContain('  BRA .next');
      expect(output).toContain('  INC'); // INA emits as INC with Accumulator mode
      expect(output).toContain('  DEC'); // DEA emits as DEC with Accumulator mode
      expect(output).toContain('  PHX');
      expect(output).toContain('  PLX');
      expect(output).toContain('  PHY');
      expect(output).toContain('  PLY');
    });

    it('should emit data directives correctly', () => {
      const builder = new AsmILBuilder('data-test');
      builder
        .section('data')
        .dataDirective('!byte', [0x0C, 0x08, 0x0A, 0x00])
        .data([0xFF, 0xFE, 0xFD], 'lookup table');

      const emitter = minimalEmitter();
      const output = emitter.emit(builder.build());

      expect(output).toContain('  !byte $0C, $08, $0A, $00');
      expect(output).toContain('  !byte $FF, $FE, $FD ; lookup table');
    });
  });

  // ==========================================================================
  // Output Format Verification
  // ==========================================================================

  describe('output format', () => {
    it('should always end with a trailing newline', () => {
      const emitter = minimalEmitter();
      const program = createAsmILProgram('test');
      const output = emitter.emit(program);
      expect(output.endsWith('\n')).toBe(true);
    });

    it('should produce clean output for empty program', () => {
      const emitter = minimalEmitter();
      const program = createAsmILProgram('empty');
      const output = emitter.emit(program);
      // Just a trailing newline
      expect(output).toBe('\n');
    });

    it('should produce valid multi-line output', () => {
      const emitter = minimalEmitter();
      const program = programWith(
        createCommentElement('test'),
        createLabelElement('start', false),
        createInstructionElement('NOP', AsmAddressingMode.Implied),
        createInstructionElement('RTS', AsmAddressingMode.Implied),
      );
      const lines = emitter.emit(program).trimEnd().split('\n');
      expect(lines).toEqual([
        '; test',
        'start:',
        '  NOP',
        '  RTS',
      ]);
    });
  });
});
