#!/usr/bin/env bash
# =============================================================================
# diag_analyze_asm.sh — Blend65 Assembly Static Analysis Tool
# =============================================================================
#
# Performs automated static analysis on ACME-formatted 6502 assembly files
# generated by the Blend65 compiler. Extracts metrics, checks stack balance,
# and detects common redundancy patterns.
#
# Usage:
#   ./scripts/diag_analyze_asm.sh <mode> <asm-file> [output-file]
#
# Modes:
#   metrics        Extract instruction counts and code size metrics
#   stack          Check PHA/PLA balance per function
#   redundancies   Detect common assembly anti-patterns
#   all            Run all analysis modes
#
# Output:
#   metrics mode:      Key=value pairs (machine-parseable)
#   stack mode:        Human-readable table with per-function balance
#   redundancies mode: List of detected anti-patterns with line numbers
#   all mode:          Combined output from all modes
#
# When [output-file] is provided, results are written to that file.
# Otherwise, results go to stdout.
#
# Exit Codes:
#   0 — Analysis completed (even if issues found)
#   1 — Invalid arguments or missing file
#
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Argument Validation
# ---------------------------------------------------------------------------

if [[ $# -lt 2 ]]; then
  echo "Usage: ./scripts/diag_analyze_asm.sh <mode> <asm-file> [output-file]"
  echo "Modes: metrics | stack | redundancies | all"
  exit 1
fi

MODE="$1"
ASM_FILE="$2"
OUTPUT_FILE="${3:-}"

if [[ ! -f "$ASM_FILE" ]]; then
  echo "Error: Assembly file not found: $ASM_FILE"
  exit 1
fi

case "$MODE" in
  metrics|stack|redundancies|all) ;;
  *)
    echo "Error: Unknown mode '$MODE'. Use: metrics | stack | redundancies | all"
    exit 1
    ;;
esac

# ---------------------------------------------------------------------------
# Output Helpers
# ---------------------------------------------------------------------------

# Buffer output so we can optionally redirect to file
OUTPUT_BUFFER=""

# Append a line to the output buffer
emit() {
  OUTPUT_BUFFER+="$1"$'\n'
}

# Flush the output buffer to stdout or file
flush_output() {
  if [[ -n "$OUTPUT_FILE" ]]; then
    echo -n "$OUTPUT_BUFFER" >> "$OUTPUT_FILE"
  else
    echo -n "$OUTPUT_BUFFER"
  fi
  OUTPUT_BUFFER=""
}

# ---------------------------------------------------------------------------
# extract_metrics() — Count 6502 instruction occurrences
#
# Extracts counts of key 6502 instructions from the assembly file.
# Only counts actual instructions (ignores comments and directives).
# Outputs key=value pairs for easy parsing by the caller.
#
# Metrics extracted:
#   asm_lines     — Total non-blank, non-comment lines
#   jsr           — JSR (subroutine calls)
#   jmp           — JMP (unconditional jumps)
#   lda_imm       — LDA # (immediate loads)
#   sta           — STA (store accumulator)
#   lda           — LDA (load accumulator, all modes)
#   pha           — PHA (push accumulator)
#   pla           — PLA (pull accumulator)
#   branches      — Conditional branches (BCC/BCS/BEQ/BNE/BMI/BPL/BVC/BVS)
#   rts           — RTS (return from subroutine)
#   data_directives — !byte and !word directive count
# ---------------------------------------------------------------------------
extract_metrics() {
  local file="$1"

  # Count non-blank, non-pure-comment lines (actual code + directives + labels)
  # Pure comment lines start with optional whitespace then ';'
  local asm_lines
  asm_lines=$(grep -cv '^\s*$\|^\s*;' "$file" 2>/dev/null || echo "0")

  # Count instructions by grepping for mnemonics preceded by whitespace
  # (ensures we're matching actual instructions, not label names or comments)
  # The trailing space or end-of-line ensures partial matches don't count
  # We use -c and || echo "0" to handle the case where grep finds nothing (exit code 1)
  local jsr jmp lda_imm sta lda pha pla rts

  jsr=$(grep -cE '^\s+JSR\s' "$file" 2>/dev/null || echo "0")
  jmp=$(grep -cE '^\s+JMP\s' "$file" 2>/dev/null || echo "0")
  lda_imm=$(grep -cE '^\s+LDA\s+#' "$file" 2>/dev/null || echo "0")
  sta=$(grep -cE '^\s+STA\s' "$file" 2>/dev/null || echo "0")
  lda=$(grep -cE '^\s+LDA\s' "$file" 2>/dev/null || echo "0")
  pha=$(grep -cE '^\s+PHA' "$file" 2>/dev/null || echo "0")
  pla=$(grep -cE '^\s+PLA' "$file" 2>/dev/null || echo "0")
  rts=$(grep -cE '^\s+RTS' "$file" 2>/dev/null || echo "0")

  # 6502 conditional branches: BCC, BCS, BEQ, BNE, BMI, BPL, BVC, BVS
  local branches
  branches=$(grep -cE '^\s+B(CC|CS|EQ|NE|MI|PL|VC|VS)\s' "$file" 2>/dev/null || echo "0")

  # ACME data directives (!byte, !word, !fill, etc.)
  local data_directives
  data_directives=$(grep -cE '^\s+!(byte|word|fill)' "$file" 2>/dev/null || echo "0")

  emit "asm_lines=$asm_lines"
  emit "jsr=$jsr"
  emit "jmp=$jmp"
  emit "lda_imm=$lda_imm"
  emit "sta=$sta"
  emit "lda=$lda"
  emit "pha=$pha"
  emit "pla=$pla"
  emit "branches=$branches"
  emit "rts=$rts"
  emit "data_directives=$data_directives"
}

# ---------------------------------------------------------------------------
# check_stack_balance() — Verify PHA/PLA balance per function
#
# Stack imbalance is one of the most dangerous 6502 bugs — it silently
# corrupts return addresses and causes random crashes.
#
# Algorithm:
#   1. Identify function boundaries (non-local labels, i.e., labels that
#      don't start with '.')
#   2. Count PHA and PLA within each function
#   3. Report imbalance if PHA count != PLA count
#
# Output: Table with per-function PHA/PLA counts and balance status
# ---------------------------------------------------------------------------
check_stack_balance() {
  local file="$1"
  local current_func=""
  local pha_count=0
  local pla_count=0
  local line_num=0
  local func_start=0
  local imbalance_count=0
  local func_count=0

  # Header for the table
  emit ""
  emit "  Function                        PHA  PLA  Balanced?"
  emit "  ──────────────────────────────  ───  ───  ─────────"

  while IFS= read -r line; do
    line_num=$((line_num + 1))

    # Detect function labels: non-local labels (don't start with '.')
    # Pattern: starts with a letter or underscore, ends with ':'
    # Skip local labels (start with '.') and ACME directives (start with '!' or '+')
    if [[ "$line" =~ ^[a-zA-Z_][a-zA-Z0-9_]*: ]]; then
      # Report previous function if it had any PHA/PLA activity
      if [[ -n "$current_func" ]]; then
        _report_function "$current_func" "$pha_count" "$pla_count"
        if [[ "$pha_count" -ne "$pla_count" ]]; then
          imbalance_count=$((imbalance_count + 1))
        fi
        func_count=$((func_count + 1))
      fi

      # Start tracking new function
      current_func="${line%%:*}"
      pha_count=0
      pla_count=0
      func_start=$line_num
    fi

    # Count PHA/PLA (only for actual instructions, not in comments)
    # Match lines with PHA/PLA preceded by whitespace (actual instructions)
    if [[ "$line" =~ ^[[:space:]]+PHA ]]; then
      pha_count=$((pha_count + 1))
    fi
    if [[ "$line" =~ ^[[:space:]]+PLA ]]; then
      pla_count=$((pla_count + 1))
    fi

  done < "$file"

  # Report last function
  if [[ -n "$current_func" ]]; then
    _report_function "$current_func" "$pha_count" "$pla_count"
    if [[ "$pha_count" -ne "$pla_count" ]]; then
      imbalance_count=$((imbalance_count + 1))
    fi
    func_count=$((func_count + 1))
  fi

  emit ""
  if [[ "$imbalance_count" -eq 0 ]]; then
    emit "  ✅ All $func_count functions have balanced PHA/PLA"
  else
    emit "  ❌ $imbalance_count of $func_count functions have PHA/PLA imbalance!"
  fi

  # Return imbalance count via a special output line (for machine parsing)
  emit "stack_imbalances=$imbalance_count"
}

# Helper: Format a single function row in the stack balance table
_report_function() {
  local func_name="$1"
  local pha="$2"
  local pla="$3"

  # Only report functions that use the stack (PHA > 0 or PLA > 0)
  if [[ "$pha" -eq 0 && "$pla" -eq 0 ]]; then
    return
  fi

  local status
  if [[ "$pha" -eq "$pla" ]]; then
    status="✅"
  else
    status="❌ IMBALANCE!"
  fi

  # Truncate long function names to 30 chars for alignment
  local display_name="$func_name"
  if [[ ${#display_name} -gt 30 ]]; then
    display_name="${display_name:0:27}..."
  fi

  printf -v row "  %-32s %3d  %3d  %s" "$display_name" "$pha" "$pla" "$status"
  emit "$row"
}

# ---------------------------------------------------------------------------
# detect_redundancies() — Find common assembly anti-patterns
#
# Detects:
#   1. STA/LDA pairs: Store then immediately reload same address (wasted cycles)
#   2. JMP-to-next: Jump target is the very next instruction (wasted 3 bytes)
#   3. Dead code after JMP/RTS: Unreachable instructions before next label
#   4. Redundant LDA: Loading same immediate value twice without intervening store
#
# Output: List of findings with line numbers, plus total count
# ---------------------------------------------------------------------------
detect_redundancies() {
  local file="$1"
  local prev_line=""
  local prev_line_num=0
  local prev_stripped=""
  local line_num=0
  local redundancies=0

  # Track state for dead-code-after-jump detection
  local after_unconditional=false

  # Track last LDA immediate for redundant-load detection
  local last_lda_imm=""
  local last_lda_imm_line=0

  emit ""
  emit "  Redundancy Patterns Detected:"
  emit "  ─────────────────────────────"

  while IFS= read -r line; do
    line_num=$((line_num + 1))

    # Strip inline comments for cleaner matching
    local stripped
    stripped=$(echo "$line" | sed 's/;.*//' | sed 's/[[:space:]]*$//')

    # Skip blank lines and pure comment lines for pattern matching
    if [[ -z "$stripped" || "$stripped" =~ ^[[:space:]]*$ ]]; then
      prev_line="$line"
      prev_line_num=$line_num
      prev_stripped="$stripped"
      continue
    fi

    # --- Pattern 1: STA/LDA pair (store then immediately reload) ---
    # Previous line: STA $xx (or STA addr)
    # Current line:  LDA $xx (or LDA addr) — same address
    if [[ "$prev_stripped" =~ ^[[:space:]]+STA[[:space:]]+(.+)$ ]]; then
      local sta_addr="${BASH_REMATCH[1]}"
      # Trim trailing whitespace from captured address
      sta_addr=$(echo "$sta_addr" | sed 's/[[:space:]]*$//')
      if [[ "$stripped" =~ ^[[:space:]]+LDA[[:space:]]+(.+)$ ]]; then
        local lda_addr="${BASH_REMATCH[1]}"
        lda_addr=$(echo "$lda_addr" | sed 's/[[:space:]]*$//')
        if [[ "$sta_addr" == "$lda_addr" ]]; then
          emit "    Line $prev_line_num-$line_num: STA/LDA pair — redundant reload of $sta_addr"
          redundancies=$((redundancies + 1))
        fi
      fi
    fi

    # --- Pattern 2: JMP-to-next (jump target is the very next instruction) ---
    # Previous line: JMP .label
    # Current line:  .label:
    if [[ "$prev_stripped" =~ ^[[:space:]]+JMP[[:space:]]+(\.[a-zA-Z0-9_]+) ]]; then
      local jmp_target="${BASH_REMATCH[1]}"
      if [[ "$stripped" =~ ^${jmp_target}: ]]; then
        emit "    Line $prev_line_num-$line_num: JMP-to-next — $jmp_target is next instruction"
        redundancies=$((redundancies + 1))
      fi
    fi

    # --- Pattern 3: Dead code after unconditional JMP or RTS ---
    # If previous instruction was JMP or RTS, and current line is NOT a label,
    # then current line is unreachable dead code.
    if [[ "$after_unconditional" == true ]]; then
      # Check if current line is a label (reachable entry point)
      if [[ "$stripped" =~ ^[a-zA-Z_.][a-zA-Z0-9_]*: ]]; then
        # This is a label — execution can reach here, stop flagging dead code
        after_unconditional=false
      elif [[ "$stripped" =~ ^[[:space:]]+(LDA|LDX|LDY|STA|STX|STY|PHA|PLA|TAX|TXA|TAY|TYA|JSR|JMP|RTS|RTI|BRK|NOP|CLC|SEC|CLI|SEI|CLV|CLD|SED|INX|INY|DEX|DEY|ADC|SBC|AND|ORA|EOR|CMP|CPX|CPY|ASL|LSR|ROL|ROR|BIT|INC|DEC|PHP|PLP|TSX|TXS) ]]; then
        # This is an actual instruction after an unconditional jump — dead code
        emit "    Line $line_num: Dead code after unconditional jump/return"
        redundancies=$((redundancies + 1))
      fi
    fi

    # Detect unconditional transfers (JMP, RTS, RTI, BRK) to start tracking dead code
    if [[ "$stripped" =~ ^[[:space:]]+(JMP|RTS|RTI|BRK)[[:space:]] || "$stripped" =~ ^[[:space:]]+(RTS|RTI|BRK)$ ]]; then
      after_unconditional=true
    elif [[ ! "$stripped" =~ ^[[:space:]]*$ ]]; then
      # Any non-blank line that's not after an unconditional jump resets the flag
      # (but only if it's not dead code itself — handled above)
      if [[ "$after_unconditional" == false ]]; then
        : # Already not tracking
      fi
    fi

    # --- Pattern 4: Redundant LDA immediate (same value loaded twice) ---
    # If current line loads the same immediate as a recent LDA #, and no STA/STX/STY
    # intervened (meaning A still holds that value), flag it.
    if [[ "$stripped" =~ ^[[:space:]]+LDA[[:space:]]+(#.+)$ ]]; then
      local current_lda_imm="${BASH_REMATCH[1]}"
      current_lda_imm=$(echo "$current_lda_imm" | sed 's/[[:space:]]*$//')
      if [[ "$current_lda_imm" == "$last_lda_imm" && -n "$last_lda_imm" ]]; then
        emit "    Line $line_num: Redundant LDA $current_lda_imm — same value already in A (loaded at line $last_lda_imm_line)"
        redundancies=$((redundancies + 1))
      fi
      last_lda_imm="$current_lda_imm"
      last_lda_imm_line=$line_num
    elif [[ "$stripped" =~ ^[[:space:]]+(STA|TAX|TAY|PHA|ADC|SBC|AND|ORA|EOR|ASL|LSR|ROL|ROR) ]]; then
      # These instructions use or modify A, so the tracked LDA value may no longer apply
      # STA uses A (value preserved), but context changes — reset to be safe
      # ADC/SBC/AND/ORA/EOR/ASL/LSR/ROL/ROR modify A
      last_lda_imm=""
      last_lda_imm_line=0
    elif [[ "$stripped" =~ ^[[:space:]]+(LDA|PLA|TXA|TYA) ]]; then
      # These overwrite A with a new value
      if [[ "$stripped" =~ ^[[:space:]]+LDA[[:space:]]+(#.+)$ ]]; then
        : # Handled above in the LDA # block
      else
        last_lda_imm=""
        last_lda_imm_line=0
      fi
    fi

    # Reset dead-code tracking when we hit a label
    if [[ "$stripped" =~ ^[a-zA-Z_.][a-zA-Z0-9_]*: ]]; then
      after_unconditional=false
    fi

    prev_line="$line"
    prev_line_num=$line_num
    prev_stripped="$stripped"
  done < "$file"

  emit ""
  if [[ "$redundancies" -eq 0 ]]; then
    emit "  ✅ No redundancy patterns found"
  else
    emit "  ⚠️  $redundancies redundancy pattern(s) found"
  fi

  emit "redundancies=$redundancies"
}

# ---------------------------------------------------------------------------
# Main Dispatch
# ---------------------------------------------------------------------------

# Clear output file if specified (we append, so start fresh)
if [[ -n "$OUTPUT_FILE" ]]; then
  : > "$OUTPUT_FILE"
fi

case "$MODE" in
  metrics)
    extract_metrics "$ASM_FILE"
    ;;
  stack)
    check_stack_balance "$ASM_FILE"
    ;;
  redundancies)
    detect_redundancies "$ASM_FILE"
    ;;
  all)
    emit "=== METRICS ==="
    extract_metrics "$ASM_FILE"
    emit ""
    emit "=== STACK BALANCE ==="
    check_stack_balance "$ASM_FILE"
    emit ""
    emit "=== REDUNDANCIES ==="
    detect_redundancies "$ASM_FILE"
    ;;
esac

flush_output
