/**
 * Code Generator - Final Concrete Class
 *
 * Translates IL programs into ASM-IL (structured 6502 assembly).
 *
 * **Inheritance Chain:**
 * CodeGeneratorBase → MemoryOps → ArithmeticOps → BitwiseOps
 * → ComparisonOps → ControlFlowOps → FunctionOps → IntrinsicsOps → CodeGenerator
 *
 * @module codegen/generator/generator
 */

import { ILProgram, ILFunction } from '../../il/index.js';
import { AsmILProgram } from '../asm-il/index.js';
import { IntrinsicsOpsGenerator } from './intrinsics.js';

/**
 * Code Generator for translating IL to 6502 assembly.
 *
 * Generates ACME-compatible assembly from typed IL instructions.
 * Uses static frame allocation - all memory addresses are
 * predetermined by the frame allocator.
 *
 * @example
 * ```typescript
 * const generator = new CodeGenerator();
 * const asmProgram = generator.generate(ilProgram);
 * ```
 */
export class CodeGenerator extends IntrinsicsOpsGenerator {
  // ==========================================================================
  // Public API
  // ==========================================================================

  /**
   * Generates assembly for an IL program.
   *
   * Produces a complete, runnable C64 program with:
   * 1. BASIC SYS stub at $0801 (so LOAD+RUN works)
   * 2. Entry function (main) emitted first at $0810
   * 3. Optional JSR __global_init before main code (if globals exist)
   * 4. Remaining functions
   * 5. Global init section (if needed)
   *
   * By emitting main() directly at the SYS entry point ($0810),
   * we eliminate the need for a JMP main startup section, saving
   * 3 bytes and avoiding an unnecessary jump on every program start.
   *
   * @param program - The IL program
   * @returns ASM-IL program output
   */
  public override generate(program: ILProgram): AsmILProgram {
    this.reset(program.moduleName);

    // Generate file header comments
    this.generateFileHeader(program);

    // Generate BASIC SYS stub so the program can be loaded and run
    this.generateBasicStub();

    // Partition functions: entry point (main) first, others after.
    // This places main() directly at the SYS target address ($0810),
    // eliminating the need for a JMP main startup section.
    const entryPoint = program.entryPoint || 'main';
    const entryFunc = program.functions.find(f => f.name === entryPoint);
    const otherFuncs = program.functions.filter(f => f.name !== entryPoint);

    // If global init exists, emit JSR to it before main's code.
    // Execution will fall through into main() after the JSR returns.
    const hasGlobalInit = program.globalInit && program.globalInit.length > 0;
    if (hasGlobalInit) {
      this.asm.section('startup');
      this.asm.jsr('__global_init', 'Initialize global variables');
    }

    // Emit main (entry point) function first — directly at the SYS address.
    // If the entry function wasn't found, fall back to emitting all functions
    // in source order with a JMP startup (defensive handling).
    if (entryFunc) {
      this.generateFunction(entryFunc);
    } else {
      // Entry function not found — emit legacy JMP startup as fallback
      this.generateStartup(program, hasGlobalInit);
    }

    // Emit remaining functions after main
    for (const func of otherFuncs) {
      this.generateFunction(func);
    }

    // Generate global init if present
    if (hasGlobalInit) {
      this.generateGlobalInit(program);
    }

    // Emit runtime math routines that were referenced during code generation.
    // The 6502 has no native multiply/divide/modulo instructions, so these
    // operations use software subroutines whose implementations must be
    // appended to the assembly output.
    this.generateRuntimeRoutines();

    return this.asm.build();
  }

  // ==========================================================================
  // File Header
  // ==========================================================================

  /**
   * Generates the file header comments.
   *
   * @param program - The IL program
   */
  protected generateFileHeader(program: ILProgram): void {
    this.asm.section('header');
    this.asm.comment('Generated by Blend65 Compiler v2');
    this.asm.comment(`Module: ${program.moduleName}`);
    this.asm.blank();
  }

  // ==========================================================================
  // BASIC SYS Stub
  // ==========================================================================

  /**
   * Generates a standard C64 BASIC SYS stub.
   *
   * This produces the standard BASIC line "10 SYS 2064" at $0801,
   * which is required for the C64 to execute the program when the
   * user types LOAD "...",8,1 followed by RUN.
   *
   * Memory layout:
   *   $0801: BASIC SYS stub (13 bytes)
   *   $0810: Program code starts (= SYS 2064 target)
   */
  protected generateBasicStub(): void {
    this.asm.section('basic');
    this.emitSectionHeader('BASIC SYS Stub');

    // Set BASIC program start address
    this.asm.directive('*=', 0x0801, 'BASIC program start');

    // BASIC line: 10 SYS 2064
    // Format: [next-line-ptr:word] [line-number:word] [SYS-token] [space] ["2064"] [null] [end-of-program:word]
    this.asm.dataDirective(
      '!byte',
      [
        0x0c, 0x08,       // Next line pointer: $080C
        0x0a, 0x00,       // Line number: 10
        0x9e,             // SYS token
        0x20,             // Space
        0x32, 0x30, 0x36, 0x34, // "2064" in PETSCII/ASCII
        0x00,             // End of BASIC line
        0x00, 0x00,       // End of BASIC program (null pointer)
      ],
      '10 SYS 2064'
    );
    this.asm.blank();

    // Set code start address (must match the SYS address = $0810 = 2064)
    this.asm.directive('*=', 0x0810, 'Code start');
    this.asm.blank();
  }

  // ==========================================================================
  // Startup Code
  // ==========================================================================

  /**
   * Generates the program startup routine.
   *
   * This is the code that executes when SYS 2064 is called from BASIC.
   * It calls __global_init (if there are global variable initializers),
   * then calls main(), then returns to BASIC with RTS.
   *
   * @param program - The IL program
   * @param hasGlobalInit - Whether global init exists
   */
  protected generateStartup(program: ILProgram, hasGlobalInit: boolean): void {
    this.asm.section('startup');
    this.emitSectionHeader('Program Startup');

    // Call global initializers if present
    if (hasGlobalInit) {
      this.asm.jsr('__global_init', 'Initialize global variables');
    }

    // Tail-call the program entry point.
    // Uses JMP instead of JSR+RTS — saves 1 byte and ~12 cycles.
    // When main's RTS executes, it returns directly to BASIC
    // because BASIC's return address is already on the stack from SYS.
    const entryPoint = program.entryPoint || 'main';
    this.asm.jmp(entryPoint, false, 'Run program');
    this.asm.blank();
  }

  // ==========================================================================
  // Header Generation (legacy alias for backwards compatibility)
  // ==========================================================================

  /**
   * Generates the program header (legacy - now split into separate methods).
   *
   * @deprecated Use generateFileHeader, generateBasicStub, generateStartup instead
   */
  protected generateHeader(program: ILProgram): void {
    this.generateFileHeader(program);
  }

  // ==========================================================================
  // Function Generation
  // ==========================================================================

  /**
   * Generates code for a single function.
   */
  protected generateFunction(func: ILFunction): void {
    this.currentFunction = func;

    // Start a new section for this function
    this.asm.section('code');
    this.emitSectionHeader(`Function: ${func.name}`);

    // Function label
    this.asm.label(func.name);

    // Generate each instruction
    for (const instr of func.instructions) {
      this.generateInstruction(instr);
    }

    // Ensure function ends with RTS if not already
    const lastInstr = func.instructions[func.instructions.length - 1];
    if (!lastInstr || lastInstr.opcode !== 'RETURN') {
      this.asm.rts('implicit return');
    }

    this.asm.blank();
    this.currentFunction = null;
  }

  // ==========================================================================
  // Global Init Generation
  // ==========================================================================

  // ==========================================================================
  // Runtime Math Routines
  // ==========================================================================

  /**
   * Emits runtime math subroutine implementations that were referenced
   * during code generation.
   *
   * The 6502 has no native multiply, divide, or modulo instructions.
   * When the code generator emits `JSR __mul8` (etc.), it tracks the
   * routine name in `usedRuntimeRoutines`. This method emits the actual
   * subroutine code for each referenced routine, so ACME can resolve
   * the labels.
   *
   * **Routines:**
   * - `__mul8`: 8-bit multiply using shift-and-add ($FE × $FF → A)
   * - `__div8`: 8-bit divide using shift-and-subtract ($FE ÷ $FF → A quotient)
   * - `__mod8`: 8-bit modulo using shift-and-subtract ($FE % $FF → A remainder)
   *
   * All routines use ZP addresses $FE (operand 1) and $FF (operand 2).
   */
  protected generateRuntimeRoutines(): void {
    if (this.usedRuntimeRoutines.size === 0) {
      return;
    }

    this.asm.section('runtime');
    this.emitSectionHeader('Runtime Math Routines');

    if (this.usedRuntimeRoutines.has('__mul8')) {
      this.emitMul8Routine();
    }
    if (this.usedRuntimeRoutines.has('__div8')) {
      this.emitDiv8Routine();
    }
    if (this.usedRuntimeRoutines.has('__mod8')) {
      this.emitMod8Routine();
    }
  }

  /**
   * Emits the __mul8 routine: 8-bit unsigned multiply.
   *
   * Algorithm: shift-and-add.
   * Input:  $FE = multiplicand, $FF = multiplier
   * Output: A = low byte of product ($FE × $FF)
   * Clobbers: A, X, $FE, $FF
   */
  protected emitMul8Routine(): void {
    this.asm.comment('__mul8: 8-bit multiply ($FE * $FF → A)');
    this.asm.label('__mul8');
    this.asm.lda(0x00, 'immediate');           // LDA #$00 — clear accumulator (result)
    this.asm.ldx(0x08, 'immediate');           // LDX #$08 — 8 bits to process
    this.asm.label('.__mul8_loop');
    this.asm.lsr(0xff, 'zeroPage');            // LSR $FF — shift multiplier right, bit 0 → carry
    this.asm.bcc('.__mul8_noadd');             // BCC — skip add if bit was 0
    this.asm.clc();                            // CLC — clear carry for addition
    this.asm.adc(0xfe, 'zeroPage');            // ADC $FE — add multiplicand
    this.asm.label('.__mul8_noadd');
    this.asm.asl(0xfe, 'zeroPage');            // ASL $FE — shift multiplicand left
    this.asm.dex();                            // DEX — decrement bit counter
    this.asm.bne('.__mul8_loop');              // BNE — loop if bits remain
    this.asm.rts();                            // RTS — return with result in A
    this.asm.blank();
  }

  /**
   * Emits the __div8 routine: 8-bit unsigned divide (quotient).
   *
   * Algorithm: shift-and-subtract (restoring division).
   * Input:  $FE = dividend, $FF = divisor
   * Output: A = quotient ($FE ÷ $FF)
   * Clobbers: A, X, $FE
   */
  protected emitDiv8Routine(): void {
    this.asm.comment('__div8: 8-bit divide ($FE / $FF → A quotient)');
    this.asm.label('__div8');
    this.asm.lda(0x00, 'immediate');     // LDA #$00 — clear remainder
    this.asm.ldx(0x08, 'immediate');     // LDX #$08 — 8 bits
    this.asm.asl(0xfe, 'zeroPage');      // ASL $FE — pre-shift dividend
    this.asm.label('.__div8_loop');
    this.asm.rol();                      // ROL A — rotate dividend bit into remainder
    this.asm.cmp(0xff, 'zeroPage');      // CMP $FF — compare with divisor
    this.asm.bcc('.__div8_nosub');       // BCC — skip if remainder < divisor
    this.asm.sbc(0xff, 'zeroPage');      // SBC $FF — subtract divisor
    this.asm.label('.__div8_nosub');
    this.asm.rol(0xfe, 'zeroPage');      // ROL $FE — rotate result bit into quotient
    this.asm.dex();                      // DEX — decrement bit counter
    this.asm.bne('.__div8_loop');        // BNE — loop if bits remain
    this.asm.lda(0xfe, 'zeroPage');      // LDA $FE — load quotient result
    this.asm.rts();                      // RTS — return with quotient in A
    this.asm.blank();
  }

  /**
   * Emits the __mod8 routine: 8-bit unsigned modulo (remainder).
   *
   * Algorithm: shift-and-subtract (restoring division), returns remainder.
   * Input:  $FE = dividend, $FF = divisor
   * Output: A = remainder ($FE % $FF)
   * Clobbers: A, X, $FE
   */
  protected emitMod8Routine(): void {
    this.asm.comment('__mod8: 8-bit modulo ($FE % $FF → A remainder)');
    this.asm.label('__mod8');
    this.asm.lda(0x00, 'immediate');     // LDA #$00 — clear remainder
    this.asm.ldx(0x08, 'immediate');     // LDX #$08 — 8 bits
    this.asm.asl(0xfe, 'zeroPage');      // ASL $FE — pre-shift dividend
    this.asm.label('.__mod8_loop');
    this.asm.rol();                      // ROL A — rotate dividend bit into remainder
    this.asm.cmp(0xff, 'zeroPage');      // CMP $FF — compare with divisor
    this.asm.bcc('.__mod8_nosub');       // BCC — skip if remainder < divisor
    this.asm.sbc(0xff, 'zeroPage');      // SBC $FF — subtract divisor
    this.asm.label('.__mod8_nosub');
    this.asm.rol(0xfe, 'zeroPage');      // ROL $FE — rotate result bit (keeps algorithm consistent)
    this.asm.dex();                      // DEX — decrement bit counter
    this.asm.bne('.__mod8_loop');        // BNE — loop if bits remain
    // A already contains the remainder
    this.asm.rts();                      // RTS — return with remainder in A
    this.asm.blank();
  }

  // ==========================================================================
  // Global Init Generation
  // ==========================================================================

  /**
   * Generates the global initialization section.
   */
  protected generateGlobalInit(program: ILProgram): void {
    if (!program.globalInit || program.globalInit.length === 0) {
      return;
    }

    this.asm.section('init');
    this.emitSectionHeader('Global Initialization');

    this.asm.label('__global_init');

    for (const instr of program.globalInit) {
      this.generateInstruction(instr);
    }

    this.asm.rts();
    this.asm.blank();
  }
}