/**
 * Code Generator - Final Concrete Class
 *
 * Translates IL programs into ASM-IL (structured 6502 assembly).
 *
 * **Inheritance Chain:**
 * CodeGeneratorBase → MemoryOps → ArithmeticOps → BitwiseOps
 * → ComparisonOps → ControlFlowOps → FunctionOps → IntrinsicsOps → CodeGenerator
 *
 * @module codegen/generator/generator
 */

import { ILProgram, ILFunction } from '../../il/index.js';
import { AsmILProgram } from '../asm-il/index.js';
import { IntrinsicsOpsGenerator } from './intrinsics.js';

/**
 * Code Generator for translating IL to 6502 assembly.
 *
 * Generates ACME-compatible assembly from typed IL instructions.
 * Uses static frame allocation - all memory addresses are
 * predetermined by the frame allocator.
 *
 * @example
 * ```typescript
 * const generator = new CodeGenerator();
 * const asmProgram = generator.generate(ilProgram);
 * ```
 */
export class CodeGenerator extends IntrinsicsOpsGenerator {
  // ==========================================================================
  // Public API
  // ==========================================================================

  /**
   * Generates assembly for an IL program.
   *
   * @param program - The IL program
   * @returns ASM-IL program output
   */
  public override generate(program: ILProgram): AsmILProgram {
    this.reset(program.moduleName);

    // Generate header section
    this.generateHeader(program);

    // Generate each function
    for (const func of program.functions) {
      this.generateFunction(func);
    }

    // Generate global init if present
    if (program.globalInit && program.globalInit.length > 0) {
      this.generateGlobalInit(program);
    }

    return this.asm.build();
  }

  // ==========================================================================
  // Header Generation
  // ==========================================================================

  /**
   * Generates the program header.
   */
  protected generateHeader(program: ILProgram): void {
    this.asm.section('header');
    this.asm.comment('Generated by Blend65 Compiler v2');
    this.asm.comment(`Module: ${program.moduleName}`);
    this.asm.blank();
  }

  // ==========================================================================
  // Function Generation
  // ==========================================================================

  /**
   * Generates code for a single function.
   */
  protected generateFunction(func: ILFunction): void {
    this.currentFunction = func;

    // Start a new section for this function
    this.asm.section('code');
    this.emitSectionHeader(`Function: ${func.name}`);

    // Function label
    this.asm.label(func.name);

    // Generate each instruction
    for (const instr of func.instructions) {
      this.generateInstruction(instr);
    }

    // Ensure function ends with RTS if not already
    const lastInstr = func.instructions[func.instructions.length - 1];
    if (!lastInstr || lastInstr.opcode !== 'RETURN') {
      this.asm.rts('implicit return');
    }

    this.asm.blank();
    this.currentFunction = null;
  }

  // ==========================================================================
  // Global Init Generation
  // ==========================================================================

  /**
   * Generates the global initialization section.
   */
  protected generateGlobalInit(program: ILProgram): void {
    if (!program.globalInit || program.globalInit.length === 0) {
      return;
    }

    this.asm.section('init');
    this.emitSectionHeader('Global Initialization');

    this.asm.label('__global_init');

    for (const instr of program.globalInit) {
      this.generateInstruction(instr);
    }

    this.asm.rts();
    this.asm.blank();
  }
}