/**
 * Code Generator - Final Concrete Class
 *
 * Translates IL programs into ASM-IL (structured 6502 assembly).
 *
 * **Inheritance Chain:**
 * CodeGeneratorBase → MemoryOps → ArithmeticOps → BitwiseOps
 * → ComparisonOps → ControlFlowOps → FunctionOps → IntrinsicsOps → CodeGenerator
 *
 * @module codegen/generator/generator
 */

import { ILProgram, ILFunction } from '../../il/index.js';
import { AsmILProgram } from '../asm-il/index.js';
import { IntrinsicsOpsGenerator } from './intrinsics.js';

/**
 * Code Generator for translating IL to 6502 assembly.
 *
 * Generates ACME-compatible assembly from typed IL instructions.
 * Uses static frame allocation - all memory addresses are
 * predetermined by the frame allocator.
 *
 * @example
 * ```typescript
 * const generator = new CodeGenerator();
 * const asmProgram = generator.generate(ilProgram);
 * ```
 */
export class CodeGenerator extends IntrinsicsOpsGenerator {
  // ==========================================================================
  // Public API
  // ==========================================================================

  /**
   * Generates assembly for an IL program.
   *
   * Produces a complete, runnable C64 program with:
   * 1. BASIC SYS stub at $0801 (so LOAD+RUN works)
   * 2. Startup code at $0810 that calls global init + main
   * 3. Function code
   * 4. Global init section (if needed)
   *
   * @param program - The IL program
   * @returns ASM-IL program output
   */
  public override generate(program: ILProgram): AsmILProgram {
    this.reset(program.moduleName);

    // Generate file header comments
    this.generateFileHeader(program);

    // Generate BASIC SYS stub so the program can be loaded and run
    this.generateBasicStub();

    // Generate startup code (calls __global_init then main, then returns to BASIC)
    const hasGlobalInit = program.globalInit && program.globalInit.length > 0;
    this.generateStartup(program, hasGlobalInit);

    // Generate each function
    for (const func of program.functions) {
      this.generateFunction(func);
    }

    // Generate global init if present
    if (hasGlobalInit) {
      this.generateGlobalInit(program);
    }

    return this.asm.build();
  }

  // ==========================================================================
  // File Header
  // ==========================================================================

  /**
   * Generates the file header comments.
   *
   * @param program - The IL program
   */
  protected generateFileHeader(program: ILProgram): void {
    this.asm.section('header');
    this.asm.comment('Generated by Blend65 Compiler v2');
    this.asm.comment(`Module: ${program.moduleName}`);
    this.asm.blank();
  }

  // ==========================================================================
  // BASIC SYS Stub
  // ==========================================================================

  /**
   * Generates a standard C64 BASIC SYS stub.
   *
   * This produces the standard BASIC line "10 SYS 2064" at $0801,
   * which is required for the C64 to execute the program when the
   * user types LOAD "...",8,1 followed by RUN.
   *
   * Memory layout:
   *   $0801: BASIC SYS stub (13 bytes)
   *   $0810: Program code starts (= SYS 2064 target)
   */
  protected generateBasicStub(): void {
    this.asm.section('basic');
    this.emitSectionHeader('BASIC SYS Stub');

    // Set BASIC program start address
    this.asm.directive('*=', 0x0801, 'BASIC program start');

    // BASIC line: 10 SYS 2064
    // Format: [next-line-ptr:word] [line-number:word] [SYS-token] [space] ["2064"] [null] [end-of-program:word]
    this.asm.dataDirective(
      '!byte',
      [
        0x0c, 0x08,       // Next line pointer: $080C
        0x0a, 0x00,       // Line number: 10
        0x9e,             // SYS token
        0x20,             // Space
        0x32, 0x30, 0x36, 0x34, // "2064" in PETSCII/ASCII
        0x00,             // End of BASIC line
        0x00, 0x00,       // End of BASIC program (null pointer)
      ],
      '10 SYS 2064'
    );
    this.asm.blank();

    // Set code start address (must match the SYS address = $0810 = 2064)
    this.asm.directive('*=', 0x0810, 'Code start');
    this.asm.blank();
  }

  // ==========================================================================
  // Startup Code
  // ==========================================================================

  /**
   * Generates the program startup routine.
   *
   * This is the code that executes when SYS 2064 is called from BASIC.
   * It calls __global_init (if there are global variable initializers),
   * then calls main(), then returns to BASIC with RTS.
   *
   * @param program - The IL program
   * @param hasGlobalInit - Whether global init exists
   */
  protected generateStartup(program: ILProgram, hasGlobalInit: boolean): void {
    this.asm.section('startup');
    this.emitSectionHeader('Program Startup');

    // Call global initializers if present
    if (hasGlobalInit) {
      this.asm.jsr('__global_init', 'Initialize global variables');
    }

    // Tail-call the program entry point.
    // Uses JMP instead of JSR+RTS — saves 1 byte and ~12 cycles.
    // When main's RTS executes, it returns directly to BASIC
    // because BASIC's return address is already on the stack from SYS.
    const entryPoint = program.entryPoint || 'main';
    this.asm.jmp(entryPoint, false, 'Run program');
    this.asm.blank();
  }

  // ==========================================================================
  // Header Generation (legacy alias for backwards compatibility)
  // ==========================================================================

  /**
   * Generates the program header (legacy - now split into separate methods).
   *
   * @deprecated Use generateFileHeader, generateBasicStub, generateStartup instead
   */
  protected generateHeader(program: ILProgram): void {
    this.generateFileHeader(program);
  }

  // ==========================================================================
  // Function Generation
  // ==========================================================================

  /**
   * Generates code for a single function.
   */
  protected generateFunction(func: ILFunction): void {
    this.currentFunction = func;

    // Start a new section for this function
    this.asm.section('code');
    this.emitSectionHeader(`Function: ${func.name}`);

    // Function label
    this.asm.label(func.name);

    // Generate each instruction
    for (const instr of func.instructions) {
      this.generateInstruction(instr);
    }

    // Ensure function ends with RTS if not already
    const lastInstr = func.instructions[func.instructions.length - 1];
    if (!lastInstr || lastInstr.opcode !== 'RETURN') {
      this.asm.rts('implicit return');
    }

    this.asm.blank();
    this.currentFunction = null;
  }

  // ==========================================================================
  // Global Init Generation
  // ==========================================================================

  /**
   * Generates the global initialization section.
   */
  protected generateGlobalInit(program: ILProgram): void {
    if (!program.globalInit || program.globalInit.length === 0) {
      return;
    }

    this.asm.section('init');
    this.emitSectionHeader('Global Initialization');

    this.asm.label('__global_init');

    for (const instr of program.globalInit) {
      this.generateInstruction(instr);
    }

    this.asm.rts();
    this.asm.blank();
  }
}