#!/usr/bin/env bash
# =============================================================================
# vice/mon.sh — VICE monitor script generation
# =============================================================================
#
# Generates VICE monitor (.mon) files dynamically based on what memory
# regions need to be dumped for verification.
#
# Usage: source scripts/vice/mon.sh
#
# After sourcing, the following are available:
#   generate_mon_script()      — Create .mon file with memory region dumps
#   generate_mon_from_json()   — Create .mon file based on expected.json regions
#
# =============================================================================

# ---------------------------------------------------------------------------
# generate_mon_script() — Create a VICE monitor script for memory dumps
#
# Generates a .mon file that dumps all standard C64 memory regions.
# Uses the -initbreak approach: moncommands are deferred until the
# specified address is reached, so dumps capture post-execution state.
#
# Arguments:
#   $1 — Output path for the .mon file
#   $2 — (optional) Path to expected.json for custom dump regions
#
# Output:
#   Writes the .mon file to the specified path.
#   Prints the path to stdout for capture.
#
# The generated .mon file includes:
#   - Standard region dumps (zeropage, screen, color, VIC, SID, sprites, CIAs)
#   - Register dump via `r` command (captured by -monlogname)
#   - `quit` to cleanly exit VICE (exit code 0)
#
# Note: VICE save command creates files with a 2-byte load address header.
# When reading dump files, add +2 to all offsets for the header.
# ---------------------------------------------------------------------------
generate_mon_script() {
  local mon_file="$1"
  local expected_json="${2:-}"

  cat > "$mon_file" << 'MON'
; ==========================================================================
; Blend65 Diagnostic — VICE Monitor Commands
; Generated by diag_vice.sh
; ==========================================================================
;
; NOTE: All dump files include a 2-byte load address header.
; When reading values, use: file_offset = (addr - region_start) + 2
;
; NOTE: VIC-II color registers ($D020-$D02E) have undefined upper nibble
; on readback. Always mask with & $0F when comparing color values.
; ==========================================================================

; Dump zero page ($00-$FF) — compiler temp variables and work area
save "dump_zeropage.bin" 0 0000 00ff

; Dump screen memory ($0400-$07E7) — 40x25 character grid
save "dump_screen.bin" 0 0400 07e7

; Dump color RAM ($D800-$DBE7) — per-character color attributes
save "dump_colorram.bin" 0 d800 dbe7

; Dump VIC-II registers ($D000-$D030) — video chip state
save "dump_vic.bin" 0 d000 d030

; Dump SID registers ($D400-$D41C) — sound chip state
save "dump_sid.bin" 0 d400 d41c

; Dump sprite pointers ($07F8-$07FF) — 8 sprite data pointers
save "dump_sprite_ptrs.bin" 0 07f8 07ff

; Dump CIA1 registers ($DC00-$DC0F) — keyboard, joystick, timer A/B
save "dump_cia1.bin" 0 dc00 dc0f

; Dump CIA2 registers ($DD00-$DD0F) — serial, VIC bank, timer A/B
save "dump_cia2.bin" 0 dd00 dd0f

; Show register state (captured by -monlogname)
; Format: ADDR A X Y SP 00 01 NV-BDIZC LIN CYC STOPWATCH
r

; Clean exit — produces exit code 0
quit
MON

  echo "$mon_file"
}

# ---------------------------------------------------------------------------
# generate_mon_with_sentinel() — Create .mon file with completion sentinel
#
# For programs that signal completion by writing a sentinel value to a
# known memory address (e.g., poke($0002, $42)), this generates a .mon
# file that uses `watch store` to wait for the sentinel before dumping.
#
# Arguments:
#   $1 — Output path for the .mon file
#   $2 — Sentinel address in hex (e.g., "0002")
#
# This uses the pattern:
#   watch store <addr> → g → (program runs until store) → save → quit
#
# Note: This is an alternative to -initbreak for programs that need to
# run to completion before dumping state.
# ---------------------------------------------------------------------------
generate_mon_with_sentinel() {
  local mon_file="$1"
  local sentinel_addr="$2"

  cat > "$mon_file" << MON
; ==========================================================================
; Blend65 Diagnostic — VICE Monitor Commands (with completion sentinel)
; Generated by diag_vice.sh
; ==========================================================================
; Watches for a store to \$${sentinel_addr} (completion sentinel),
; then dumps all memory regions.
; ==========================================================================

; Watch for program completion sentinel
watch store \$${sentinel_addr}

; Continue execution — VICE will break when sentinel address is written
g

; --- These commands run AFTER the sentinel is hit ---

; Dump zero page
save "dump_zeropage.bin" 0 0000 00ff

; Dump screen memory
save "dump_screen.bin" 0 0400 07e7

; Dump color RAM
save "dump_colorram.bin" 0 d800 dbe7

; Dump VIC-II registers
save "dump_vic.bin" 0 d000 d030

; Dump SID registers
save "dump_sid.bin" 0 d400 d41c

; Dump sprite pointers
save "dump_sprite_ptrs.bin" 0 07f8 07ff

; Dump CIA1 registers
save "dump_cia1.bin" 0 dc00 dc0f

; Dump CIA2 registers
save "dump_cia2.bin" 0 dd00 dd0f

; Show register state
r

; Clean exit
quit
MON

  echo "$mon_file"
}
